{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Data Explanation "
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "- It is prepared using real data from socio-economic data from 1990 US Census and \n",
    "  crimedata from the 1995 FBI UCR\n",
    "- This dataset contains a total number of 147 attributes and 2216 instances."
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# The columns that we worked on"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "- murders: number of murders in 1995 \n",
    "- murdPerPop: number of murders per 100K population \n",
    "- rapes: number of rapes in 1995 \n",
    "- rapesPerPop: number of rapes per 100K population \n",
    "- robberies: number of robberies in 1995 \n",
    "- robbbPerPop: number of robberies per 100K population\n",
    "- assaults: number of assaults in 1995 \n",
    "- assaultPerPop: number of assaults per 100K population \n",
    "- burglaries: number of burglaries in 1995 \n",
    "- burglPerPop: number of burglaries per 100K population \n",
    "- larcenies: number of larcenies in 1995 \n",
    "- larcPerPop: number of larcenies per 100K population \n",
    "- autoTheftPerPop: number of auto thefts per 100K population \n",
    "- arsons: number of arsons in 1995 (num\n",
    "- ViolentCrimesPerPop: total number of violent crimes per 100K popuation \n",
    "- nonViolPerPop: total number of non-violent crimes per 100K popuation"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Liberaries "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "metadata": {},
   "outputs": [],
   "source": [
    "#!pip install dash"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "metadata": {},
   "outputs": [],
   "source": [
    "# First, install the necessary packages\n",
    "import subprocess\n",
    "import sys\n",
    "\n",
    "def install(package):\n",
    "    subprocess.check_call([sys.executable, \"-m\", \"pip\", \"install\", package])\n",
    "\n",
    "# Install dash and related components\n",
    "install('dash')\n",
    "install('dash-bootstrap-components')\n",
    "install('plotly')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "metadata": {},
   "outputs": [],
   "source": [
    "import dash\n",
    "import dash_core_components as dcc\n",
    "import dash_bootstrap_components as dbc\n",
    "import dash_html_components as html\n",
    "import plotly.express as px\n",
    "import pandas as pd\n",
    "import json\n",
    "import re\n",
    "import matplotlib.pyplot as plt\n",
    "from plotly.offline import init_notebook_mode,iplot\n",
    "from pandas.io.json import json_normalize\n",
    "import numpy as np\n",
    "import plotly.graph_objects as go\n",
    "from dash import Dash, dcc, html, Input, Output\n",
    "from dash import Dash, dcc, html\n",
    "import plotly.express as px"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Reading Data"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "metadata": {},
   "outputs": [],
   "source": [
    "crimedata = pd.read_csv('crimedata.csv',sep='\\s*,\\s*',encoding='latin-1',engine='python',na_values=[\"?\"])"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Handle nulls"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Êcommunityname          0.00\n",
       "state                   0.00\n",
       "countyCode             55.12\n",
       "communityCode          55.26\n",
       "fold                    0.00\n",
       "                       ...  \n",
       "autoTheftPerPop         0.14\n",
       "arsons                  4.11\n",
       "arsonsPerPop            4.11\n",
       "ViolentCrimesPerPop     9.98\n",
       "nonViolPerPop           4.38\n",
       "Length: 147, dtype: float64"
      ]
     },
     "execution_count": 39,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "round(crimedata.isnull().sum(axis=0)*100/crimedata.shape[0],2)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Êcommunityname</th>\n",
       "      <th>state</th>\n",
       "      <th>countyCode</th>\n",
       "      <th>communityCode</th>\n",
       "      <th>fold</th>\n",
       "      <th>population</th>\n",
       "      <th>householdsize</th>\n",
       "      <th>racepctblack</th>\n",
       "      <th>racePctWhite</th>\n",
       "      <th>racePctAsian</th>\n",
       "      <th>...</th>\n",
       "      <th>burglaries</th>\n",
       "      <th>burglPerPop</th>\n",
       "      <th>larcenies</th>\n",
       "      <th>larcPerPop</th>\n",
       "      <th>autoTheft</th>\n",
       "      <th>autoTheftPerPop</th>\n",
       "      <th>arsons</th>\n",
       "      <th>arsonsPerPop</th>\n",
       "      <th>ViolentCrimesPerPop</th>\n",
       "      <th>nonViolPerPop</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>BerkeleyHeightstownship</td>\n",
       "      <td>NJ</td>\n",
       "      <td>39.0</td>\n",
       "      <td>5320.0</td>\n",
       "      <td>1</td>\n",
       "      <td>11980</td>\n",
       "      <td>3.10</td>\n",
       "      <td>1.37</td>\n",
       "      <td>91.78</td>\n",
       "      <td>6.50</td>\n",
       "      <td>...</td>\n",
       "      <td>14.0</td>\n",
       "      <td>114.85</td>\n",
       "      <td>138.0</td>\n",
       "      <td>1132.08</td>\n",
       "      <td>16.0</td>\n",
       "      <td>131.26</td>\n",
       "      <td>2.0</td>\n",
       "      <td>16.41</td>\n",
       "      <td>41.02</td>\n",
       "      <td>1394.59</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Marpletownship</td>\n",
       "      <td>PA</td>\n",
       "      <td>45.0</td>\n",
       "      <td>47616.0</td>\n",
       "      <td>1</td>\n",
       "      <td>23123</td>\n",
       "      <td>2.82</td>\n",
       "      <td>0.80</td>\n",
       "      <td>95.57</td>\n",
       "      <td>3.44</td>\n",
       "      <td>...</td>\n",
       "      <td>57.0</td>\n",
       "      <td>242.37</td>\n",
       "      <td>376.0</td>\n",
       "      <td>1598.78</td>\n",
       "      <td>26.0</td>\n",
       "      <td>110.55</td>\n",
       "      <td>1.0</td>\n",
       "      <td>4.25</td>\n",
       "      <td>127.56</td>\n",
       "      <td>1955.95</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Tigardcity</td>\n",
       "      <td>OR</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1</td>\n",
       "      <td>29344</td>\n",
       "      <td>2.43</td>\n",
       "      <td>0.74</td>\n",
       "      <td>94.33</td>\n",
       "      <td>3.43</td>\n",
       "      <td>...</td>\n",
       "      <td>274.0</td>\n",
       "      <td>758.14</td>\n",
       "      <td>1797.0</td>\n",
       "      <td>4972.19</td>\n",
       "      <td>136.0</td>\n",
       "      <td>376.30</td>\n",
       "      <td>22.0</td>\n",
       "      <td>60.87</td>\n",
       "      <td>218.59</td>\n",
       "      <td>6167.51</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Gloversvillecity</td>\n",
       "      <td>NY</td>\n",
       "      <td>35.0</td>\n",
       "      <td>29443.0</td>\n",
       "      <td>1</td>\n",
       "      <td>16656</td>\n",
       "      <td>2.40</td>\n",
       "      <td>1.70</td>\n",
       "      <td>97.35</td>\n",
       "      <td>0.50</td>\n",
       "      <td>...</td>\n",
       "      <td>225.0</td>\n",
       "      <td>1301.78</td>\n",
       "      <td>716.0</td>\n",
       "      <td>4142.56</td>\n",
       "      <td>47.0</td>\n",
       "      <td>271.93</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>306.64</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Bemidjicity</td>\n",
       "      <td>MN</td>\n",
       "      <td>7.0</td>\n",
       "      <td>5068.0</td>\n",
       "      <td>1</td>\n",
       "      <td>11245</td>\n",
       "      <td>2.76</td>\n",
       "      <td>0.53</td>\n",
       "      <td>89.16</td>\n",
       "      <td>1.17</td>\n",
       "      <td>...</td>\n",
       "      <td>91.0</td>\n",
       "      <td>728.93</td>\n",
       "      <td>1060.0</td>\n",
       "      <td>8490.87</td>\n",
       "      <td>91.0</td>\n",
       "      <td>728.93</td>\n",
       "      <td>5.0</td>\n",
       "      <td>40.05</td>\n",
       "      <td>NaN</td>\n",
       "      <td>9988.79</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 147 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "            Êcommunityname state  countyCode  communityCode  fold  population  \\\n",
       "0  BerkeleyHeightstownship    NJ        39.0         5320.0     1       11980   \n",
       "1           Marpletownship    PA        45.0        47616.0     1       23123   \n",
       "2               Tigardcity    OR         NaN            NaN     1       29344   \n",
       "3         Gloversvillecity    NY        35.0        29443.0     1       16656   \n",
       "4              Bemidjicity    MN         7.0         5068.0     1       11245   \n",
       "\n",
       "   householdsize  racepctblack  racePctWhite  racePctAsian  ...  burglaries  \\\n",
       "0           3.10          1.37         91.78          6.50  ...        14.0   \n",
       "1           2.82          0.80         95.57          3.44  ...        57.0   \n",
       "2           2.43          0.74         94.33          3.43  ...       274.0   \n",
       "3           2.40          1.70         97.35          0.50  ...       225.0   \n",
       "4           2.76          0.53         89.16          1.17  ...        91.0   \n",
       "\n",
       "   burglPerPop  larcenies  larcPerPop  autoTheft  autoTheftPerPop  arsons  \\\n",
       "0       114.85      138.0     1132.08       16.0           131.26     2.0   \n",
       "1       242.37      376.0     1598.78       26.0           110.55     1.0   \n",
       "2       758.14     1797.0     4972.19      136.0           376.30    22.0   \n",
       "3      1301.78      716.0     4142.56       47.0           271.93     NaN   \n",
       "4       728.93     1060.0     8490.87       91.0           728.93     5.0   \n",
       "\n",
       "   arsonsPerPop  ViolentCrimesPerPop  nonViolPerPop  \n",
       "0         16.41                41.02        1394.59  \n",
       "1          4.25               127.56        1955.95  \n",
       "2         60.87               218.59        6167.51  \n",
       "3           NaN               306.64            NaN  \n",
       "4         40.05                  NaN        9988.79  \n",
       "\n",
       "[5 rows x 147 columns]"
      ]
     },
     "execution_count": 40,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "crimedata.head(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "image/png": "iVBORw0KGgoAAAANSUhEUgAAAWMAAAF+CAYAAABXinukAAAAOXRFWHRTb2Z0d2FyZQBNYXRwbG90bGliIHZlcnNpb24zLjQuMywgaHR0cHM6Ly9tYXRwbG90bGliLm9yZy/MnkTPAAAACXBIWXMAAAsTAAALEwEAmpwYAABgbUlEQVR4nO2dd7gkRfWw37NLWnKQJDkIKyAgOSmiYkIQf4CAIAiKAgqLCnwmJIkoJoIIgiQBkaAgSBAkSoZll10WlpwRBSUsOez5/jjVOzU91T3dc1Pfu+d9nnnu7Z7q6pqZ7tNVJ4qq4jiO4wwto4Z6AI7jOI4LY8dxnEbgwthxHKcBuDB2HMdpAC6MHcdxGoALY8dxnAbgwtgZcERkaRF5RURG96GPV0Rk+f4cV8F5PiIiTw30eRwnjwtjZ8BR1SdUdW5VfbcPfcytqo/057j6ioh8WURuHOpxOCMDF8aO4zgNwIWx0xMi8piIHCAik0TkVRE5RUQWFZHLRWSaiPxDRBYIbZcVERWRWcL2l0XkkdDuURHZKexfUUSuF5GXROR5ETk3Op+KyIrh/9NF5HgRuTT0cZuIrBC1/YSI3B/6+W3o86sFn2NM6O8FEbkXWDf3/ndF5OFwnntF5PNh//uBE4ENgwrlxbB/CxGZICIvi8iTInJIv33pzojGhbHTF7YBNgdWArYELge+D7wHu7b2zR8gInMBxwKfVtV5gI2AieHtw4ErgQWAJYHjSs69I3BoaPsQcETo/z3ABcD3gIWA+8M5ijgYWCG8Pgnsmnv/YeBDwHzhfGeJyOKqeh+wJ3BLUKHMH9q/CuwCzA9sAewlIluXnN9xABfGTt84TlX/rapPA/8EblPVCar6JnAh8MGC46YDq4nIGFX9l6pOCfvfBpYB3quqb6hqmT72L6p6u6q+A5wNrBn2fwaYoqp/Ce8dCzxb0s8XgCNU9X+q+mRoPwNVPV9Vn1HV6ap6LvAgsF5RZ6p6napODu0nAecAm5ac33EAF8ZO3/h39P/rie258weo6qvA9tis8l9B1TA2vH0gIMDtIjJFRHYvOXcsYF+LzvVe4MnofAqUeUe0tQcej98UkV1EZKKIvBhUEathM/8kIrK+iFwrIs+JyEvhcxa2d5wMF8bOoKOqf1fVzYHFganAyWH/s6q6h6q+F/g68NtMT1yDf2EqDgBEROLtgvZLRdtLR8cuE8b2TWChoIq4B3tgAKRSHv4RuBhYSlXnw/TKkmjnOG24MHYGlWDk2yrojt8EXgHeDe9tJyKZ4HwBE3Z13eEuBT4gIlsHg+E3gMVK2p8HfE9EFgjn3id6b64whufC+HbDZsYZ/waWFJHZon3zAP9T1TdEZD3gizXH78ykuDB2BptRwHeAZ4D/YfrUvcN76wK3icgr2OxynKo+WqdzVX0e2A44CvgvsApwJyb4UxyKqSYexYyHZ0Z93Qv8ErgFE7wfAG6Kjr0GmAI8KyLPh317A4eJyDTgR5iwd5yuiCeXd0YyIjIK0xnvpKrXDvV4HKcInxk7Iw4R+aSIzC8is2OudgLcOsTDcpxSXBg7I5ENMf/g5zH/561V9fWhHZLjlONqCsdxnAbgM2PHcZwGMEvdAzYftZ1PpR1nGPD3Z+4e6iEk+eR71yh8r8qY4+Oz9mV9NoWrpp9f6m9eWxinyH+Bw+GLcRzHaRL9Ioxd+DqO0yRSM+zBlFPx+aue12fGjuOMOIZaBvVy/n4Rxo7jNI+hFki9UHfMTfmMZRPSqrp7F8aO4zh9pOyhkL131fTyPlwYO47jBAZC11x1Zlw76MNd2xxneOCubc2im2ubB304juM0ABfGjuM4DcBd2xzHcRqAz4wdx3EagBvwHMdxBoFByU3hOE7zcG+K4YXrjB3HcRqAqykcxxlxNDFRkKspHGcmZWZWUwz16ryX8/vM2HEcZxDwmbHjzKTMzDPj4Ygb8BzHcRqAB304juM0ABfGjuM4DcBr4DmO4zQAnxk7juM0ADfgOY7jNACfGTuO4zQA9zN2nBHKcFyhDtfq0P2BC2PHGaHMzEEfTcxN0Q0Ph3YcxxkEPBzacWZSZuaZ8XDEvSkcxxlxDEc1hc+MHccZcQz1hLCX83sEnuM4TgNwNYXjOE4D8KAPx3GcBuDC2HEcpwG4MHYcx2kAbsBzHMdpAP0SgecGPMdxnHIGJQLPha/jNA+PwBteuM7YcRynAbifseM4TgNwNYXjOE4DcDWF4zhOA3A1heM4TgNwNYXjOCOOmTaFps+MHcdpEkMtgzyFpuM4zjDFZ8aO4zgNwGfGjuM4DcBnxo7jOH2kTAZWDUv3mbHjOCOOwfamyPed8qa4anp5H/2Stc1xHMcpp1vWNo/AcxzHaQCuM3acEYqn0Bxe+MzYcRynAbgBz3EcpwH4zNhxHKcBuM7YcRynAfSLMHYcp3kMx0lR3TEPx89YhOuMHWeE4t4UwwtXUziO4zQAnxk7jjPi8OTyNU/uOI4zEAy1DOrl/O7a5jiO0wBcGDuO4zQAF8aO4zgNwIWx4zhOA3BvCsdxnAbgM2PHcZwG4K5tjuM4DcDVFI7jOA3AEwU5juP0kcZUh3Ycx5mZKdMOVK0O7QY8x3GcBiCqWuuAzUdt13GAG/Acx3HKuWr6+VL2vqspHGeE4vmMhxcujB3HcfqIG/AcxylkOM4WveyS4zgjDldTDB794U3hQR+O4zgNoF+8KRzHcZxyBsWbwl3bHKd5uJpieOFBH47jOA3AhbHjOE4DcAOe4zhOA3CdseM4TgNwNYXjOE4DcGHsOI7TAFxn7DjOiCPlIjeYcio+f9Xz+szYcRynAbgBz3EcpwG4msJxnBHHUMukXs7vM2PHcZwG4Dpjx3GcBuBqCsdxnAbgM2PHcZwG4NWhHcdxBoFByWfswtdxmofnMx5euJrCcRynAbhrm+M4TgPw6tCO4zh9pGxCWlVd5MLYcRynj5RpA7L3rppe3ofrjB3HcRqAe1M4juM0AJ8ZO47jNAAXxo7jOA3AXdscx3EaQL+EQzuO4zjlDEo4tOM4zcPDoYcXrjN2HMdpAC6MHcdxGoCrKRzHGXGk1B2DqcqIz1/1vO5N4TjOiGOoZdCQFSQd6g/uOI4z3HE1heM4Iw5XU9Q8ueM4jmP4zNhxnBHHUE8Iezm/u7Y5juM0AA+HdhzHGQQ8HNpxZlI8HHp44WoKx3GcBuAzY8dxRhwzrWub4zhOkxhqtYV7UziO4wxTfGbsOI7TR8oC36oaUj0Cz3Ecp4+Uybzsvauml/fhiYIcxxlxzLQGPJ8ZO47TJIZaBnkKTcdxnGGKh0M7juMMAoMSDu1qCsdpHh4OPbxwP2PHcZwG4MLYcRynAXjQh+OMUIbj0r3umIfjZyzCvSkcZ4TiOuPhhRvwHMdxGoDrjB3HcRqA64wdx3H6SGMSBTmO48zM9EeiII/AcxzHKaGuUbHo+FGLPVAagefC2HFGKO5N0Sy6hUP3izB2bwrHcZxyBiU3hQtfx2kePjMeXriawnEcZxDwrG2OM5PiM+PhhQd9OI7jNAAXxo7jOA3ADXiO4zgNwF3bHMdxBoFBMeA5jtM83IA3vHDXNsdxnEGg28zYDXiO4zgNwNUUjjNCmZnVFKl+BlOVEZ+/6nk96MNxnBHHUMugXs7vagrHcZwG4H7GjuM4DcDVFI7jOA3AXdscx3FqUNc46JU+HGcmZ2b2pmgi7mfsOI4zDHBh7DiO0wBcGDuO4zQA96ZwHMdpAG7AcxzHGQQ8habjzKTMzN4Unpui5skdx3EGgqGWQZ6bwnEcZ5jiuSkcx3EagM+MHcdxGoDrjB3HGXHMtAY8F76O4zSJoZZJbsBzHMcZpriawnEcpwG4msJxHKcBeASe4zhODXqNEuyGqykcx3FqUFe+Ze2vml7ezg14juM4DcB1xo7jOA3AZ8aO4zgNwHXGjuM4DcBnxo7jOA3AhbHjOE4DcAOe4zhOA+iXGniuM3YcxynHa+A5zkzKzFwDbzjiagrHcZwG4AY8x3GcBuDC2HEcpwF40IfjOE4DcJ2x4zgjjpm2Bp7jOE6TGOoJYi/ndzWF4zhOA3A1heM4TgPwCDzHcZxBYFAi8Fz4Ok7z8Ai84YXrjB3HcRqAz4wdx3EagM+MHcdxGoCHQzuO4zQAF8aO4zgNwIWx4zhOA3Bh7DiO0wDcm8JxHKcBeASe4zjOIOA18BxnJsUj8IYXrjN2HMdpAK4zdhzHaQAegec4jtMAfGbsOI7TANyA5ziO00fKtANVDanu2uY4jjMIeHJ5x3GcAcZnxo7jFOJ+xs2i28zY/Ywdx3EagKspHMdxGkC/qCkcx3GccgbFgOc6Y8dpHq4zHmaoau0X8LWBaj9QbYdr3z4O/4wjcRwzw2esPY46jaOT3DlQ7Qeq7XDt28fhn3EkjmNm+Ix1x+HeFI7jOA3AhbHjOE4D6FUYnzSA7Qeq7XDt28cxeH03ZRwD2XdTxjGQfQ/LcdR2bXMcx3H6H1dTOI7jNAAXxo7jOA3AhbHjOE4D6EkYi8hc/T0QZ+ARkVEislF/t+1xLKsNVN9NQkTmFZF5h3ocvRDGPs8QnXu0iHxrKM49VNQSxiKykYjcC9wXttcQkd8WtB0tIu8VkaWzV5e+/09EfiUivxSRz9cZV5d+fyIi80fbC4jIjwvanpFoe2pB24VE5DgRuUtExovIMSKyUD+N+WIR+WLVh144d1fBqarTgV9W6bNO2zCGT4rICWHsfw3/f6rkkBNF5HYR2Tv+zkv63zj7PkRk53CtLJNoN1pE3hNtzyYiXxOR+wr6XUFEZg//f0RE9s2PJ1ybha+CfvcTkaeBR4HHReQBEdkhvLdUt89bRPzZwvbOInJs+IzJ3AdVPmOu/ToiMhmYBNwjIneLyNoFbTcWkavC53tERB4VkUe6fIYtRORAEflR9sq3UdV3gc+V9ZPot5IMqXot9dh373KhZqTKbcBSwIRo3z2JdvsAzwNTgMnhNamk398CVwK7hdcVwPEFbf8PeBB4CXgZmAa8XNL3hMS+u2q07dgX9l8FHAQsF14/BP6RaDctjDP5Kuh70/CdPA6cD2wLzFHyGXcFLgMeAn4OrFPS9lBgG4InTZffu1Jb4Ohw/h2ATcJrh7DvmJLj3gccGcb9R2DzkraTAAHWCP+PA67PtdkhXBfPANcDmwFPARcCaxX0OxHL0bIi8DDwa+CyXJvTSl6nJvo8JHz25aN9ywOXAP8PeKhgLKlr5ckw/uXz12645v4efv/zgV/3+hkT3/WHou1NKLh/ganAp4FFgIWyV0nfJwJ/CJ/rYEw2nFLQ9gjgN8CHgLWyV0HbOjKk67XUh74ryYXksVUaRSe6LfydEO27O9HuobIfJNF+CtENj83YpxS0fQh4f42+JwGzR9tjSvq+G1gg2l4QmFzQdnxiX2H4I3AYsDcwDzAvsBdwYJexjwY2B86j5IGTG+8ewNXAgwVtpgHTgbfo8jCr2hZ4oOB4KRpH7jNuAzyNrbimAv+XaHdX+Psj4CvxvqjNPcCK4f+1gDeBz3c5f9bvAcA++eu7lxc2Weh4eIZr7xVgq4LjDgW+Hl0jXwufd3vguvzYgLuAucL/s5Zcq7U+I3BTlX1h/201v5tJub9zA1cWtL028bqmoG0dGdL1WupD37XkQvyqm7XtybAcVhGZDdiXoLLIt8NmKFW5H1gamwmCzb4nFbT9t6oml5wFnAVcLSKnAQrsDpxR0PaXwM0ickHY3g57Oqe4Niw7zwvb2wKXlozjk6q6frR9gojcBhyVaiwiY4AtsRtxrZIxx6wIjAWWBe5NNVDVyjrAGm3fEJH1VPX23P51gTdSB4jI6tgsYwtsNrGlqt4lIu8FbgH+kjtkmoh8D9gZ+LCIjMYEUMxbqvpQGPtdIvKoql7YZexvi8iO2Oxyy7Av32887i2AVYE5sn2qeliu2XRV7fjcqvq6iDytqhcXdP+p3DVykojcqqqHicj3w74xIvJBTCCMVtVXQ99vi8i7/fEZgdtF5HfAOdg9sz1wnYisFc51V9T2WhH5OfZ7vRl91rhNzOvh72vht/4vNoNM8RVVbVN5iMjyBW3ryJAq11KvfdeVCzOoK4z3BI4BlsCWf1cC30i0ewT78S6l/Qf6VUG/CwH3iUh2M68L3CIiF4fjtora3iki5wIX5frO37zZ/qOC/utj2EztcFX9e0HbP4jIeGx5K9gMLSnUsBnMtzFhD3ZzvCoi37auNG+0eVdEdgL+hF3gOwLJmyd8vvUJyyFsVjS9YByIyM8w9c3D2EVwuKq+WNJ+AUxFEAuUG/rQ9svYw2Ue7LoAu2BfDu+l+A3we+D7qprdoKjqMyLyw0T77YEvYjfos2I2iJ/n2iwSvv+MuePtgutvN+y6PkJVHxWR5Wj9pm2IyInAnNj18XvsRss/gACeEpGPqerVueM/iq0AipguIl8AssnAttF7WXTWv4Dsc/xPRBZX1X8FveQ7Bf1W/oyBNcPfg3P7Nwrj+Gi0L3t4rJMba9wm5m9BX/1zbGav2HeZ4gJsIhJzPpDSX9eRIVWupV77risXZjAgEXgikv8RwUZyaEH7Tcv6U9Xro7anpZvo7rUGWUB4Si5K9KBS1Sf6od9lsQfZxtgFeBOwn6o+lms3Cvg+cKSaEaNK33sCF6jq8xXafhXTkS2J6RI3AG5R1Y6bp07b0H4x7EEtwFOq+myV8fcXRdddRsn1NxuwUti8X1XfLmg3SVVXj/7ODfxFVT+Ra7cq8FfgRmA89nuvi/32WxU94MOs7xhgw3DMrcB+mA58bVW9seizhet2dlV9reQzjg393q+qbxX1NVgEo+IcqvpSbv9YbPVxFKZayZgXOEBVV030VUeG/ExV/1/u+I59vfTdF2oJ4/BE3QdbBsfCaquC9vPY2/pKl37nAl5X1ekishJ20VxedFPUQcza/TPMwCDhlXxCicg+2Gzg39isNWu7ekHflWeYNcd8i6puWKHdWFWdmi0f86SWimGVsC5wq6quGS78Q1V1+7607TbGXJ+pi67bdz0tOm42bFn5iqrOV3UsBf1+BFMBPRbGsBSwa+p3FJHbVHV9EbkVW4n8FzNgvy/Rdg5s9rVq6HcKcHZKfREds7Gq3lRh39KY7v7F8JBfB5iqqvcU9LsFZjh7OIxlOeDrqnp5Qfv5sPvgw2HX9cBheaGZ67+b6iZrOyfwHWBpVd1DRN4HrKyqf4vafA7YGtgKiFU604A/qerNBX0vil2vALer6n8K2t2lqmvl9k0quvbq9B3abkXru7su/mylVFEsa0sRfTemJ94Ms/hvCmyaaLcaMAHTsTyOzQ5WLel3PLb8W4KW9fjsgrZzYKqR3wKnZq+Svisb/KhheAS+ilmCX8AMC69TYFyoO26qezGcpPUNHXeEvxMJhk1gYl/blozxidz2MmWvGv1uDfwk8R3vit3EAhwI/A2bbb6n5NpbOdpeiYQRJrx3EDB/+G2exVQGh9X5Prp8pg4jUn4f8F3MXW5quAanAqdgwv7bBf1OJRg2w/YKmPAuGsefwzW4fHgdjK0AUm0re0eE9ueG3+WesD2m5PrbsMZ39wVM1pwRxvMosG2uzV5hfK9iOt/s9SgF8qZq31Hbn2IG9N3D6yrgp5U+Q82LpZLlFLgZ2Cza/ghwc7eLEJt1Hxj+L/qBzgcOx57yu2J66zL3qaQVuKDttcAsFdtODjf/xLA9Fji3pH3lcdPyYnibCu57NX/DCzGBcghwA7acTro5VW0LHFvwOq6/xl0wvltz2+cBZ2P2hOsxffungB8Dfyvoo8NlK78PM8DsRPBcCPtmB+brMr5KbpiYWuI7mED7dvQ6hJy3EiZ0x2B6zGnAwmH/XCTcTMN7N+S2Jb8v937HvVdyP1b2jgjv3xn+Toj2dXhkhf11JjB3A4tE2wsnvrv5sFX9ObRPAhbs8jt27Tv+PoBR0fbo1DWWetU14B0T9HJXUm45nUtVr43ev07KAxhERDbELvivhH2jC9quqKrbicjnVPUMEfkj5mtZRB2DXx3D4xuq+oaIICKzq6kLVi4ZR+Vxaw2Ph2C4+SL2MADzbvmjqv6v4JA91Ix7h4jItdgFekXBODLn9m5td8OEyZuJ93YsGHdl9VHUPmMUtjTXXLNVVHU1EZkF01lvGvZfISJFxdXuFJFTgDPD9k7YbDnmJMyH+dfhezgHeyh18xg6CvMS6eb9MxsmxGbB3NoyXqbdiAfwrppXxlvYauy/AKr6qqRjPgCmiMhl2MNKMS+hO7LvNHEvvC4im2jQUYvIxrS8IPLU8Y4AeEvMU0hD3yuQvm7AfpOpwCcx19CdSHtvgQnAWHXwXzqD2kZj32mH04GILFhyz1TpO2Z+IOtrvpJ2bdQVxh8AvoRZSjPrvtJpOX1ERA6idYHvjE3ti9gP+B5woapOCYaMawvaZnrkF8VCap/FnnZFzAu8BsRGFqXTdQrgifCaLbzKeCpYhS8CrhKRFzBDSxGVxy12V+0ELKeqh4tFbC2uOdcxEXk/cA0m1CdgAm1d4Psi8lFt19Vuic0s3haR6cAXtMDwICILJnZPDn/npnWhZdyBzco6dHkickjqHFQXVBlbRv+/g+l4P5dr8xaAqr4jIvnfosgYuhd2c+5LmDFiM7EZqOpfgb8GIbIVtrI5MQi4c1T1qoK+K7lhht/hehE5XVUf79L8rvAgnwtbDp8hIldg92CR588cmB0kezg9h/mkb0n6XtgT+EPQHYOp4nYt6LuOdwSYKuMKYCkRORszan65oG2didcVIvJ37EEJ5jFxWa5NZkwF+61jFFPJ9Np3xpHAhPDQFkx3/L2Ctm3UNeBNBVbXLpbYYNg6FIvcyS7wQ1T1hconK+77q5hOa3UsAmpu4CBV/V1f++7DmDYlzBqLvpto3B8ATqdk3CJyAvaw+6iqvj98n1eq6rq5dhcA56nqebn92wBfVNVton2TMAE8VUTWB46KZo7580/HXNQyV6n4wlVVXT7XfkFspZC05Bec4yZV3bhq+4p9/gdzHRTshvlT9hb22Rftx3OtjukQV1fV0bn3sln8psBidFmVSXCRKkIjA3mY9W+HCY8LgPWwldETWFTYq719ohn9fxDTKU8huOGp6ssVj016R0Tvj8Jm+ldjnjmCqZqSXkAicruqriciN2ABU89ixrOk0Azf+wyZo919zCtTtW+xcPXZsJWbYKrdSl5FdYXxuVgET6ElsQ4icrSq7icil5CwsGuBl0bFvo9L9Rn1vW/UNnn+1DhEZF3MGNRmiQ4W1KdVNb/EnXER5oVmydjvUtW1RGSCqn4w7LtbVdfItbtfVZOqkfx7eQtyyqIcvXcMpue/CZsN3KgVLhSJvGLCdqG7VThHV0EVtV8S00FnroE3AuNU9amoTdHsLev7jKhtkdN+1rbDsh4s6l/AVBaLY3aAc1R1Yq7daeVdt7thishzmL74HCzlgOQOKFrBjMG8Eu4vOpmIfBqbma2CfW/3Aj9T1Y6ZnViOiJ2xGeT6mHvlyQX9flRVr5GC3Bwlv+MNqvrh1HuJtl0nXmLeGL/AHiCTgf1VtcyXGxFJnl9zHjR1+o5Wnu9gq7DtNecF0426aopFgakicgftN9BWYUB1hWumxvhF1QEEHekhtG7Kf2JBDv/NNb2zap91zo8tx76c2H8vplvs8MFVc9n7Jq2onG68HQRZpldbmJZaKKZsFpR/Lx8Q0bYd68VVdVxQlXwEU0sdJyJXAieoapm66Wrg41jIL5ih6UosWCBPHfUR2M34R2xWCCY0TsPCxbNxV4lSzJgezvdHLGdEkU4UEdkD032vHMZ3YNmNpqq71RgH2ENp83COL2IGw3NUdUrJmLbErtvZgOVEZE3MsyOeOOyBBSEcSOt+WAf4qYgsqar5skDbA2uq6mvhPrsCSApjbNZ/De3qo4yy3/EqEdkf86qYcY3m9bUisjWme11PLUirSIVwKubhcEMYy3GY4bSM2Hd5Dmx1MZ7Oe7dO30dg+TxmrDxpqYUqUXdmnOw8e3KLyNqqOr5bu74gIldhX04W4bIT8BFV/XhB+w+q6oQa/Zc6x4vIZFX9QMGxHbPX6L2DsBu+9CIMbXeiPQx6W+CHqnp+rt1TtKKx2t7CAkqWitoenBpXNI6igIj5sZng4Vi0XNHNiYhMVNU1u+3rhTp9i8g6wA8wS3nsD796rt1YTABuiT1M/4ipg97JtTsNm7X+Q0siIRPjODax+yXMo+CvBcfMHsb0c0y4HlfQLhMe10WrpzZfWbEMi5skBN1C2Grn/fk+VXXtou3+QERSD/M21ZdYJshVMa+sjwGXqOrhBf21XQNlK76SMS2Fqe12zO2v3HedlWcRtWbG3YRptERfU1WPid8TkXGYu1G8rygAIOsv5YS9YO6H+XF4ihbxKxHJlpR/6jLb6HCOF5G8c/yYknOVeYxkS9PYkps0Gqjq2eFm+1jYtbWmDUEn0259j2kzohQJ2xRB3fA57IGwMDbLWUtVn+xy6KsispYG7xqxtIsdM846S+eI50VkZ1pGlB0JngQJzsZmP5NJrygAUDNwHgwcLCLbY7Ogn9EZGpsJxDUl4bGgxXkY5sAe7NlDdBtMF/sVEdlMVffLGgYhvEX4XMtiroFFs0uAd1T1pdR4IiT1sFfV/xYct0Kkv5bcdlJtGO7r0zA3u5OxCcR3VfXK1AlUtcPTIkyAYj4MrKGq74oFifwTmwykmCPoubMPNCbeLvltYp7CYiP60nfllWcRdWfGG2AX5vux5dFo4FXNuSOlngqx/jPat0z2L7Y0+0z8viYsyyLyC2zJFSfiWFVVC2d+YmG6X8CEy7yYP3BHTmMxA+VnNSSbEXO7uVRVx0ZtTsSEwA9jPaqIHIp5PHytaBzdCBfe2xoiD8Vc5T4DPF6kgwvtqkZufRILbb5aozBsEdldVU+Ntl/F/GPPwQJh2i6SEn3gupjRLPNkWBzTnY2P2hQunYHfJ5bO2XFLY/ksslDhmzGdceoauVFVN0n1k2u3BDbr/zzmMXAe5tHzSq7dteGcY8JY78au2dUxA03yXCJyDfCJbKYtZny7ElNJTFbVVcL+MzBhcDk2YUhG0uX6PgVTC30XE/L7ArOq6p5Rm9uAr6nq3blj1wBOVtX1cvtLl9WpyVi2GgzX1jewwJjTus0KgxpsM0wts6VGxtU6s8zw25QMORnmH9uTRmG5OB5T1Z177bvXlWe+UeUXdvOsiLlRjcb8S38Svb8jpn97AQtjzF7X0iWnJyUp7ML7Wa7XOCDi7fB/pcACzJPhTCy7V+r9rs7x2Oz3HGz2/OfweggTQnMn+pwXeF+0vR2wS3gtmj9/1jZ8z//DHn5XY8aUyt9dfh/mcnMDlnv4YUIqxYK2p1Mjf2/u2FkxwfIBTDjk37+XhJM9IRlLneuxZAwfw1YGO2I6vv8jl5YTW6XdhQmzFTFXrxmvgn7/BHwg2l4NOL1kHPcTBYZgHjdTw/8Tov3Tw3WdvV6me3rTOTE95R3YfXkEubSdmPX/cczGsiXwWczL6TFMfZHqdzRwVo3vOgv2OIaQrpTy9Jzrh7ZPYLaFXYnS1oY2r9GKjpscbSfzomMCdeMaY941eu1UdmydvsN3961er9u6M+M7VXWdWDclIjer6kbh/2Uwh+8jsYs8Y1r4EouySlXSsYSn6VJaI3GPmC/u9tgM+r/YDfVnTXiEiLmULUO7c/z9mFcBGmaEYRwfouXQPUVzqf6iPk/Cog9PD9sPYTOgMdhSM57JzNBHi8jhmFD4RljGjdecrlosUGYjzE/719Fb82I3xhpR28nAB9V8cOfH9KP3q+q3ClYttTxAwjFzYpFjy2hx3oH7NKerLHtPanjFRMechakHphD5w2vkxSAij0X9Zn8latuhPqqrExeRr2DJxa8LfX8Y+An2MD9EVQ9IHVcXMWPvXJpwQQurwr1pz5FxvJa4W4n51G6pFZIJBX36Eth9vwYmkK7TnK5ZRI7AVqdPYJ//Qkx3nlJbLJPfF6Pp1VClfC69UKdvEblWVTfr5Tx1vSleC4JhoogchcXmz9CThi/pcWwp2RVpT3DTpo8J/bXpe1RVReRC0in0isiML59Q1bKgDKjoHB/G8ev8BVfAutiyPGOaqu4DtpzOtY2FzkcJuktVfUvM9zdPncitWbKHoVqCmS2xfLnnkwhw0foeIGDf9Xhav/9TmL40TpTysoisoeml87REn7FXzKF0pnVMsUb+wZVHVZet0E+e+0Tk95jxWDGPjsKgDlU9RSwwZD3suv5+dA0mBXH4Hj4UNm9Q1aQLnlgAxJ6YG9V4YD4R+ZWqtum7g9D9UcXPl/EYcFPQF8fG5pTe8yvYMv8RNS+MBUl7G30Nm9icgIWmvyEiyYdsSthW4Eox//q/aJcZZpgkHInZLOLkRkUeG5X7xvKh/4ZOQ31X3XXdmfEymLCaDfgWNjP8rQYda9Suqm65F33P8djS8I7KAx8Aqo5Dct4XIrKaBp2giNyjqqtF752FObY/g5XnWS5c4PNjZWGKPDWW6XYBi8jfgJ9rTu8nVg/w+6raEd4pNTxAQvts5TRjpi05DxMR2QQzsGWCW7EH1q7AzlqeJrJjBl/Q7mSsBFFRRFpmNHo7u7lEZDPM+DRFVZPh4WKZ2PailZHrBszd741cu9rZ9MJx47BKLZlO/vNYMqgOj4psRi7mebM2dr2M13Zvil4M5IX6T+2i9xSzsewI7BBf1+G90Zgb447YRONazA1yqaIVs9TLuDgNmxi+i12zZW1vxB7qv8YmWrthsjD5uWv2nZJpSVmWatXvL9K65SNK2qdK1CRrvmE6x3cwvWehHilqvzGWOekBLPfEo9hTPDkOqicmuTf8OKXjwIw9iyX2L5Fvj6kuvovpddeI9m8EfKnkM14FzB9tLwD8PdH3mILjlyjY/2jilfzuQvubw3myxE8rYBFT+XaLYbkG/owJnsNT31HiuFK7QtTuPiw0+v6i34aoxBY2S70ZUymUZtkKn2/lLuc/Ofy9NvEqy+w3ifZkRHMVXduYumFWbOWxafaZcm2WCa+jwusD4fVT4EcVvse5KrRZHFOT3Y5VdTmYSK9ecp9tG37/f2O5VFLtapVYq/oiZOUjKlMF/LO/z1N7XDU/RF6wPZK6OWllZpoU7euata3bvtwF1vYq6btywUTqZVarNA5sKXsHNpuaJ7w2Dfu+lGt7dfj7s5q/y4Qq+6LfcK5obL8q+/5qjmNzzDD2HDb7fQzzAe+vm6iqMO762xBlOMMmD2PC/7NQLAC3wgT8o2F7TeDifvx8k4kmIUFoFdW12xcLV74Mm6ktUyRQqFHTLry3ITbZeCJsr4GtgOM2e2BBHw9gWfFWz76Xmp95Hix/dKVxl/Qj4Xo+KGwvhQWMJPvFDHN/Ab6JrUDu76e+F8VSml4etlch1Nnr9qqrMz4FU0+MpzjxCnTRLWdIqzJEXl88L2YtjttmyWsyvaICL2r4xCW8pAVJtBPUyaz2eFhyv09VTxOLkps70e4sEXkeu2CzCgX3YDOT/LgWD+5FW4lIlmMh7qtI7zRdRJbWYNgM6qSi7+UEYI2gmzwQ+03/QCJaKDLILa2qX0sZ5HLju0pE7qKVd2Acud+9ZOmcLf3ygRnTQnvBrpOXc+1TWd66XRNguutMZfQ8Jvhex4RxUUaugzH973XYySeKJXdv/yAFIcIzBlfspngacFuwi4DlbD6loI9jMV/kjMeDqiXFXNKehW0jyn3ij8YypV0cznW3dIYQH4/VKvyiqt4Z+i383qXdB7cqdTIu/paQzwWbUL0Sxrhuou1+mHzZN7T9KMWJkOr2fTr2O/4gbD+AqfmSv2NMXWFcVbB9CVNPfBMT3kthvpB5Pokp+5fEioFmwudlrPRQTKZfjAXU3GKpEb+qufJFEXUKJtbJrHYw5nO6Mvblz4oZdjqS36jpIJN6yBw/wtQUS9IZWacU1xX7AXCjiGT64A9jBpMU76iqilVTOEbNyFR0IZ6Gfe9ZOHPKIAfM8OxYAjM6XSqWSOdYzBi1VNT0swXnSqI10olGXErrWpkDs/TfT+thCGb8OjtcP//BbvzrsRneTwr6rRJoAe0hwlti7p4ZSkEwh6r+Koxh4zD23bQgelQsj0SKwxL7vgKcKq0sbC/SCkJKoqpP5j5nfvL1Xszb6FdiOTvOo7yoZ/Y7rowJsSyYZEtM956iTsj8+hryuYTxvyCdwSSE9zI7zyvB42VuLU+GVLlvLG/NeWIFT1HzXiqbuLYNrM6S4qeYhX9DzNixFhaZ1dfl2TZ9OPb/sGxpRe9X1tthlRMWwITZI9hNumdB24nYDTMh2pfSGe9Bu5/xqVhI7KSi746wHKr5PbwHE3RbUlDVIrS7Hot+ewDT3Y6meClcKRF4uCbuw7xW7qBVumocBbr/Hj7fBsA80fbc2E1S5di1gN8l9o/GVFjjsHzM2xPp3hPtT8GCFCZh5baOA07scu4JVcbYw/fxnej1A2yW2s0HfF66JMQP7S7AHsB3YQb4/bFglKL2S4Y248N18JOStlfmfsd5yu7fGt/HbeH3zOwVCxd995hb57zY6mAqtnI/oJ/6vg5ThWZtN8CM790/Q80PXCrYCIaSoldJvz+h0wD14xrjqqRL7M8XwTAVfelJYwumkpg1/P/FcMEuhFmSC40GmH7yF+H12YI2i2BLyr9hrjrzVhj3Ypjq4UNhe2lgl4K2VQ1y9xKEbvjtXid6ABX0HQc3ZK8nMf/T5RPtJ0CrDBWmSqj8u5e1pYJRLrTrGmjRy7VJItAjvF7DZuNVPt/sdBptv132KunrPZjO/9/YhOQsqpcjWxk4uOT9qYQSXtG4O0pAYQ/JGzAV0nPYJOIzJf3uhM22nwq/y/3AdgVtJ0bH/Aqb0ZfJpzp9r4XppF8Kfx/A0qx2/e7qqik+ruUVi2stQSM+raoz1BJqy4DPYNbtUsQq9Kbcskp1VBr5TIa2L6lqm15HrEDpaFU9OtHFeSLyO2B+sRDf3UlnuHpHW4VVPwv8QS3D3D+CPj31mY7EdJNnh13jxMKb80mq/4AJ9+NC38dSnKgbmOF3GmdoeyL0k+IQqiUCf12De1f47e5X1QfLxhHG8Aw2SxEsLHkx7EI/FcsYFyMarvZwnuli4cUd5H77UdgN8lxB267Zz6JzvobNQn+Qf68vaE4VI1bId2/MP/3C5EGdzElnnpPaKh6xPC8rYtfpThXafwOrH/di2PUfCr7rwJnA7UEvrpjxrO36k/rZ5tD2fC5CcT4XgFlFZFZMJ/8bVX27TN9dte9gNxoV+s3c8QqrjXccH13f3RtbxqULsOVQ1QoNVfqdBKyrqm+G7THYEnnVqE1KuC6AzSB/o7lsYkW+khka+UyKyD2YyiCfoW12rChnkT/m5pg+S7BZSUfFh2DQ2gILEX8cSxg/JbyXjEYL38ea2p4XeEJ+HFIvq1RmCEuixeWOFqJLInAReZF2vd+H4+2UYJNQaTm371ZV3UDSuZv/gi0BTwi79gY2U9WtE33Hv31WFeTPmqjMLNWyn12cPy4m//mklUI2i9S8oax9dNz8mHFpF+wh9WvtTA2btY0NoaOxpfNhqvqbsrGWITWypUXHtF2DYd8ELfEHF0sgleXzuEFzenGpkW1OLF3lSbRyDn9FS/zLwzH7Yn7Zd2P35tJYCPiHcu0q9y2We/knmCfWclhOkNLrJk/dmfHq2AzmFLFw2VMxXVKb8lvSZdU7gj4izgKuFgutVGyWeUauTf4pr5iBbWdVnZzo81itXllE84I47HxTclYMqZ/M+kfY03005gaVCeJNMb10EfPTvY6WiFUBycY4Ot6OL+Zs9iUih2Hf25mh3U4UzKCCEDonjLssd/Lnctu/LGmbMV1EvoA93KE9YjD10NgTm/n/MLx/NQVGSq2RoY5qRrkNKUn+nuAXBf8nEasOkemsT8XC1l/qcli8Cn0HK/FUFDyxEvYQW1StRuDqwFbamSyrTra0jFEiMmPVEiYO3UqWTcT0tLOEY2Z4AmVDzgtiKMw2dzymr74Bm5j9GnMMKESre6LU6Xs/LGHZc2Jl486mZaSsRhVdRoFu5MOYn+OrmOBcsaTt1pQo9UObT2EX7i+BT1Y4/7xEhoDE+//BHONPxpbWK5W0nUwuaU/Yvyg54xZ2ge6B6cb2p6CEee6YWehMhjIXicRC4b0dsFn06eG7fRSLasq3e4xWIEv+VRTY0lHhO7Uv7N8Uc+t5HPOi2Jb+M8gtj3kZZDrBS7Dl8RgKkthU6PM0omCd3CtZPp4KRjnsQfqp8FtMILgpVhjPuIr7Xg2/5cHU0+2ugXksfZMSvSSmb12PdkNsRyVpOhNGVdF3/zxcGx/DVhjnAb8sab9P+M2nUByQcxtR0FPu897eD2Meh8kPCb//XVi6hJ6/j17GkX/VVVOMxqb1u2EuX2diT4APYcJ2pZJjb1XVDRL7t8ZuwslqGf27jWEd7KabB/syXwR213S5o5Uwq3D2Whi4FXMmPypqtwvmc/gd7IcBCzE9CkuqckbUdqLWSGYtNX1OpVUn7J+YC5BQo45WN0TkZuyJ/ydshrkj8A0NyZ4KjhmN3Wh7AJ/SYpVGyof4JWxl8GMtWHJXHPcZmCB7MWwvgN30u0dtUu6TS2OzltGqumSi3zkxHXDmPvX3MNYOlUZoXyn5e2hbNZXsIZSrkDpm+lIvdPoOVV1X2sPU267jsO81LOoN7LpbIWwnfcDDMaMw/W6mT70SS4WatC2JJcpav+xakBoh8yLyCDYpyvhFvJ2/v8IxldJ+1ulbWvUXM3aItzWR0KpjXDWF8SOYB8UpmqsELCLHZieUdFn1TTWX+ahHHdUkTHj8M2xvgkUHJfW60XErYLmBx2Hhv2Ny738a8/FdDfvxp2Bhsflad1OxmzFbL52Nzawy1cBdufanRZsdPqeaq4cWjqlcJyy0z9QNy6vqYWK5fxfTXDXp0HZZLIVhVrbqJqwqyGMFfY8J484qj/xNQ6KjRNujMH/UP4ZdO2Dfy0vYbHfLqO3CmDBZlvZqHEn/1wIh1rEvem95zFf9w9jy8hTttAmMxnT9ySoxubb55O8XY7aTDhWViGTlkzbBHqoZ8wDvVjlfhfFMAjbUoD4SKwhwS4HAvBybPZ+v5i+7Lab//HSu3TJl59TeEvjkx3ItsLmWZHAM7RbFBGVptjmpWW8wHDNJVVcXq8N4napeWHB9Ve5batRfLKKuMJ4RxRPtSyUxjz9EZkA5WXNpK8UMZ2topKPSLpnQJFFVuGBfNhveEAs6eASbFd+KLSFSN+Y47ZKRX3pIbhQdWyg8cu3qJuipVE26LmLRT+tjHhXnYRduKntc1r7wt5HOhEk3Y4KqLZpTVf9c0PfdWGj1C2F7Qcx/M59W9P3YTPeD2Oz1rLIbP+jFv6QlOlqpmfxdekwlW2X2H7WdjBm93wjbc2DG5o5sdeHBdBJ2P7yAqbF2LnkALwf8K+p7DKbGeyxqc56qfqFgNUTR5EgsKf7KWGBOHITVcd+FB8wb2Sw7zMLn0BpVyAvGcBoV0n72lTDebgElM6hrwDsWmx3FHJffp9ULMr6VfdFq2ckKDSPSyoB1u5hL2TnYRbA9ITw1x42YyuFXwEXdfsDwQNiSdE25uN1m4UveMP8QqkDVJ19283Ut0RToGiEkIgeq6lFSkB+4YBl1GhbuWi2CyCIi11fV28I516MVIp4XQHOq6v+r2C+YLeEWsZSfYNFfR8QNwnvrYMvJb2FCft7ssip4mL0BTBarrRg/+OLv40vhvZWAfaPLNBmSrTVTyUasri0Xsex3LHp4n0b10OlHgI8H4TZKVVOpSmPOp72I7LthX/xwHxf+1nVnfSK8ZqO7oe9q2gvczkmuwK3UcGGNyNJ+zopdL+/B7DNJROQnWI28F8P2AsB3VLXD9VYqpjZNUUkYSyuJ+cK5Dz8v9lTJt18eWwpvgN34t2AZ8PPeA2OlVTJdsJpbk0jrqPIW+th9KSXk3ktLV7ynmE/qXWEstyTGAhVzkar5uP6C+jdbJTSRcLsLVapJZ66Idapm3wB8T8za3TU3BRbBeKqY77dggQtfDULgyFzbv4nIZ7S87t0MVPUPInInprsWrHJH3s1oXew72B/T/8cP96KH2aXhVXbuDj/2KkiNFJCBUSKyQG72n7xH1UKnr8NUIcnQaRHZWS03yrdz+2f0UTCOWeKVo1o+7TbBqar/Cn9rqS60nqfLHBqVwFLVV8IKOqaXMOvdsYfJkphnxwaYXCjS/9eJg1hFVV8WS216GSG1KZ11FTuoOjOuk8QcTGd4PGZUANMdnoMteWOSFR9SaM3s+UG39Jfwygw1u2MJypcj8RCh9cQ9LO6KdE6ISgmnpd3ndHnJ+axqe2n1vF/j7lrNn/tYLDhgEbGKCtvSeaE8Ec7XobsSkb0K+s0MKF1zU4S+7wA+IJYDQeJZHp1J6scB3xeRN7GcIKWCSsz1aFWCPj8hiNEeEsarJYSaDZv1QomTvlie7inZzDI8dFbNVgIJjsIqZlT1yf8lNiHI3P1Ss/8Fo83HwmvGe7nZfya46gZ/PCciW2nwkxXLY9LmXy6dfutC6zov+x0XxoI5VqU9sXvqHuta4DYT7iJyJRYrkP02h9AqBJtnHCa4bw0r3bGYXChitIjMru1xELMXtK0VUBJTO7l8lSehlDj0l/WNhdD+I3zYWVLLKTHH+F3oNPzsm2s3HzZzzWbHH8Qswzdj3hQX0AekYsJpqVHkMcz8vkfLr/GrqlrqMxkdO5aWRfvqvAAQM75upzmvE7FCqltqwiNEKiSLD/uSM7DoM5aqfrp8riWwB+ob2INBMLXYGKy01NNR20KvljCOjuRQIvIRzGXtsdD3UlhKx45ZVVADrZU9fIO66s7Udxfe79Chd0NEVgU2o/U73pt7/1FaQm9xWsVfs+tv+ajtT7IZnYhsromgpIIxrIAZpt8b+n0SC5l/qPTAan1fia0898eW87sCz6VUVlKhwG3Udipmf8oE5uxYHpWxibaZd8lETMX3ppSXzzoQux9PoxUHcbFGHllR20oBJcnzVBHGInK0qu4XzfLa0M4IpJ9iLmeZ+9T22JPk+NA+H1mzB+bAv6CqrhCWwyeq6scSY7kZM8JNJlqK52d8IvJcaHdzeN2uqh1l43PHLIpF0bxXVT8tIqtguuGu6e+6ISLjVPWYsn1SoypueH/Boveg/XsOs4rzgZ1U9RaxteoJ2Ixwa03XT8u8XG5S00mvAJyjnVWFv66qv5MKFSIywR3+bzP+isg3NRdBFnSif9VQQzDavwuWYOpz0b7MuDoHFas4i0XgfVFV7w/bK4XP2GHMSd2wkovWy713DBbifRHdU0Bmx4zG/NvjicYTBW1nPCQL3p9x/XS7lgqOnxuTEaU6ZqlYKiq0Ha+qa0t7Hc3rVTU5aQmzzJWx33FqyarlB1iNvQtphVmfq6p59Vh2Te2GuTx+FDNqzqqqn0m0FUydsSqmvxbMON7VDTfqY0bJs9J2FYXx2qo6vmiWp52lfB4t6a7t6R3aT8Sc0m+LZmBt1veoba2LSkS2U9Xzu+0L+y8n5CJV80OcBXOUT40jcydbTlUPF5GlgMU14U5WNO78zSQ1fSZzs6QZzUjMkkL71bGL9RuYWxnAjlpQeFIs3PuHWILsKwm5KVT1ulT7KpQJiILv6H5VXbmgr+R7Yrmgj9AQmSmWDnV/Vf1yom2HMC0SsFIjJDu0T7lGqRa77+1DK+Pdu5C0ncTtuz2sawnjXlY4UsPfObTPQt7/jqnXngEuUNUVojYfVdVrpMBHP3EfZAJzYdofChPyxybGsykW4XpFyX0wPvVwLmjb84Suks44WxbkhW5J+7oGqDfVjASAPUko9jw4M8yk/0b7bCPp9oUt+/OCN7UP6uUirZRwWlo+p8tJu754Hqxadcz1tOfCjbeVXB7XOt9zmEU/hS0LLwL+gfmezi0iye9PE8niNZGbIjrHcliE1bK0z+zilZMU/J/ahrRuP1MRJN8DxmoUIq+q94glAEpxp5i71ZlheydMHZKickh2OG9Vr6KMcZiBtOfgmByLBMEq0f/x+PLCNUs4X0fH/BVsqZ/5O/+McmPYj8VUiN8JbebFZqgxm2JVRLakk9R9oCJyURCYHaqoMirKtFtFZF2tVnfzdAYjubyIbIxl8lomHFs0A5uV9sKN12H5ZIuyF10vIt/HKjlsjs04Lilo+xZmmfwBLYHdYSkXC+L4DLCEiMRx6PPS6WaV8apYMpJMJ7gBFrCQomrC6ZuxOPz30O4RMg0LB51BDzfvDMTcbd5Hu1Ek1nvGyfmnYcbU28N22/cnFjQSkwm2OaUzj0DMRdhFdwmd3hwzhlXwf2ob4BKxAqP7aXuAw68xa3WKOlWc98JWCvti38UN2IO2c+DmJ79DQT8dSPWcEBlPUny9ZX3GArWbgD2ZlmCN/0+iqr8Lf+t4PAjtieezGX3ROTLj70uYbhwR2S/X5uDwt879UEdg1mUz4Osi8jjmZVW2Yuk5uXxdA95UEmWX8k/ycCPMSivZz5ewyKOvFvQ7CnvCzsiAhoVUdgxORB7GBGHhDC20WwPzJTyM9lLl04BrNZFESMwAdBymH5qCLXu2TenAROQ2zDB4RxDKC2O6pDId3qK0Zs63a2cQTC8+k4hljOpw1dEqFWnT/WWO/Hn1x8LAIqpaNFvtMNwm2mQht0Ir3Jawvbyq5ss0zYq5xX0Z890FM4qcgVW17lhaSsUqznWRGkEZ4f3rsWKnv4vUb20VwXPtuwZESL1shB06+DJyk5ZU3x2+6OGa3ZVWqs+tsarpR9c47xOqunS0Xfs+EMv0thJ2jXQTmLWQgshETTgziLkbbgNcFeTCBlhNy1JDPgxc2aV1td3ifo1YBFURY7DQ0pNhhhFjDJZcO8+Ugv1tqOrdwN1iyvpXtRXFM5pit5R7sYvqNUxoX4QtM1JUcSebgYhsh+mAr8MulONE5ABt9+ropcQQ1HDVkbTHwUvA4xqMDNoZ1bYsZiH+OMUliQCOCcLiSopLXFV2ZwzHvg3sLxaVuCL23T2kJUE8qvqGiJwIXKbBMJdHWv7tRX2kbuI6QRlggS23S3ssU5khp2tARM1Z6+5AnZSaReqZQrSCv3MF8jPpXu6DT3dv0huZ0BWRRYhWngV8G/N1XkFEbiJM6KqeqPKLimWXML3NCtH28pRnPLqVKIMZ5tOcrCaNCcAHgN9hAvFYLF1mf/R9HvB7bFmyGebze35J32OxJe436VJSHLPsLxJtL0yihFEvL2x2DjYrnj37v+T7eAsL/hgf/r8DCxf/RK7t+zAd2H1YQMesXcZxJKaXvp7uJa4+ndiXLHEVvb8Rpn/fJXsVtNuKLlWcw3c1AZu5jqVCtfHwGy4QbS9IQcmq8P7l2Ow/q5SyLaFqcD/85ithOut7wvbqwA9zbfpUAQcTikWZBdcP38crmI54lT6c54l++D6WTr366bveCngQm3E/iqngppS0nwVbXa/W7Z6JX3VnxtkSdJ1on9IZFHEAVgg0i3JbFnMlKaJKpE3GReFVlTp9r6ztM/pru8zoH8QCX4ryssaM0na1xH8pqEIs1SMYM54S87++CLhKRF6g5ZuZ5zEsSUyWV3kV7Pc6HDOMXCnmffAD7II6KrSvovf6PKZqSFqlcxwkIm+q6jVhHP8Pq+5xYqqxiJyJCbaJtFRkSrpKycF0qeKsqmuGFcSOWJDSveHvlVrshtQ1JDvHN7AH+lgReRq7kTuqZ0iBy2g01q0Su08mqEBCm0liobixPnp1aVXTbjsl5YEZq2EGzQVtU57DHnxToma18ghLcXEDwVbBqWOWxNSGWVKrGzE10VOJ5pfSUq0VFaHtlcOxe/EfqvpBsQCkHQvGPBqzVS2LyYVPBAN5V1/7WsJYq0fB3YRdJJmf8O8wgVJE10ibaAwdEWRdyPe9TlHfwAQR2UBVbw1t1w+fpQMpcEPCZigprhBz5zknbG9PsQGqagQjAKqatTtEzNd2PoqrUY+NbypVvVdEPqiqj0TL6bsxY9KlmFBbL15qa3E6wLuxpPj/KXg/ZissJPoALFfw2LCviHWw2VcVI0elKs6qOhX7DQ8Wke0xwf4zCkJXtVpIdty+LScEdt1tT0v3ndE1AX2CKiqQyVohMVWCk7A8ytcCiAXGnEx7vopR2goiOT8zWBWhvVX5Pg27F7YL2zuHfZsn+s+r1tbCUnv2B2+rJbYfJSKjVPVaMa+RFJcQ8p1QbMROUteb4kep/ap6WG7XH7AZY5YOc0fsSbsdafbDftC2SJuCMWS+tfkxFCXRiftWLKoo2Tcm7HYRkWx2uzRmmZ9MpzGglhuSqh4gFj6dlWE/SVUvLGguqnpmtH2WiHyzrP9gTFoK03VPw5ZIKTef+8WyvGW5VrcHHhCLWMq8XZIGqQosCkwVkTto1xl3CFlVfV5EtsJc7MZjhtIyQXsPFkDxrwrjuEdEvoiFsb4P85S4Od9ILLpvB+yh9wJmnC76TZAKIdmh3bzYrHgJ4K/YZ/wGNpO8m1ZtQ6DlXiUFgUGY2ifP82JBOJnnz7ZU+26qMFcmiMP4rgsPlJj5pd0PuG1bSwJbarCwqsa+2qdLzvOiCFW9SyyCrz94USwA5gbgbLHcxUWrpyW1R6NhXW+K70Sbc2AZm+7TnDVZ0iGzHfty71eNtFkoN4btsMi95IMiWNb3wZZQLxN8IDVdDy1pNc3QyHoqFfOy9oLUj2A8HPM2eITW01g14U0hFmq+Ny2Dy42YK9cb2GzrlfwxNcadtBhre8h3frk6G3ZhK+VL52sx3e/tdBH00p4wPvPOOTz+zcU8HebB7AQX0CpxlfUbRy9WDskO7f+KCfdbsNXhAuFzjlPVianPF46rlIw+7F+eLmkxReQg7ZIfvGAcF2IP8mxCsDOwjkbBLdJDHuEexvEPzGaRrSZ3xAyEqcjc2ANjFFYcYkGtmE6gyzjmwn77LNBrPqwIa8dELMyYr1bVK2ufp44wTpx4dsww8snc/tOxcOZ4ub+rqu5d0tdqWKRX7Ceb0gemjr1RE6Gu4b3zMCGczUZ2xIwwRbP0bufKfvRVqZCXtWgm32reijzKHVOE5lcBInI/8IGKutrKiPnJ7k9nEEepy1yYGcbtiwJy6oylq6Cv2d9jtPupz3iL3HcsNUKyw/4Z0aNBh/g8ZkxKhhVLH5LRS0laTGmPwDtOC4oCJI5bAPPGmVE0FDhU0+6gy6nqo9329YKYv/tvMIcBxVY34zTtUnYwrd8xLkL7Zr7tQCIin8f820dRIQFWTF0DXp5UeXCot9zPvsiPYML4MsxN5UYSxhlpd80ahekSy/RRdY1y3cjOlXJDSgnddXLbo7AY+v0xa34HWj+C8R4q6mqlM3AnO2fqdzwfM6j9nnbH/qK+v4appl7HZugdASW59t0CVWJWwIoPPFhy/ouL3gt9bxX9v2xZ2xyrRHr5uL8/iOVEyPN21OZdEXm0SBAHKgcGZUguYZa00mLG+vxYodw1YVFYRe5JKIOG5eztVmb+z3TmOL8Am5n2jLTKsR2fWv0kuAyr7LIsrev6uxTbcKqMoczoWCRgf4k9PCZXtG/MoK7OOM7qP5pQHjzR9FN1+sVcftbA8kDsJhYc8fuCtr+k8wlYNsutbJSrgrZS9iVzXiTa/ze8NwoLfjkA8wjYokTnOBrL+LQs7QKzyCJ7JPY576HLEh6LkOsI3CngHVU9oUubmAOwlJKlATkAUhCoQjpdKdh3sXNQJY3HZpD/zC3761ZxzmYy12io9BGE3EdU9aKoWd2Q7DWk5cUgWGTpyxTcxGGm97hYDtxntL3CxpJEaTIjLiORMCtH3WXvGdiD5J/YhOj9dIYqE8Y2FlsdzpfTHc9Ld1/cUqS9HNvhIrJeBXXLWdgE5x5qGs6K0N6Mjg9i7oa1VQ61U2hGm6XlwWsNopXSbjzm3zsN+0Adbinh6b0N7YJKtdOImLW/D1MntM3SsR+sY5ZeY8wp/V5q36yYQexb2Gz/SFV9uEvfl5GwyGqBw7+ITME8VvLtO5bwUiFKLmp7CDbbvpAKeUBE5ArMw6BrUE54sGeBKpmb2aGqWmRczY4bgyWm2R+rZTg6em80ZmnfEZsRXYplYJuS6iscM1E7M7G16WlF5NeYf/p+2hmS/YZWKDZZBTFPjY0ydZNYeP1NmiiflbrWEm3Koh1TK9RYvTILFiWaPIdYjuOtMQ+YeEUyDStN1WEwrYr0Vo6tUFU5mAQV7fKYj3lpWak8dV3bHpeW1X4WYFExH7payTlixNZXk8KM5GRs1vMKZqhJcRFm3LoLE1jdqDtLL0Xq57x4NOw/GnsgrCEWqg0UWp3rWmSfV9XSUNaIa0Xk55hBqihKLmPX8PeAaF+h2gFLwHSzWKh43HdKWL2hFimHWOLuqSKSzM4GICI/xJbac2Pqnf1p16+i5gt9BeZGmFVxvk5Eyqo4p3y98/fFgdjq43Gx/AQQhWQXjbkHulbYiKiSMKtWtCPt6pV3pMQ1UFX/CvxVRDZU1TK31V6oXI4t4mCxNAxXUzFd6QDxaHhVKSvVRt2ZcWa1f5jI+NHNoFOh3xkp6sSc8+fVgpyoUhLbPxhIK+fFzzAHe8WW+//Gihq+kGt/OuUGvA6rs9S0yIrIr7AL8GK6CFhJF1Tt+A3DEnw7VT23yhjCMbdjs//SXNOh7YVUzCkb2t+FPdQuxVy9btW0R0zlKs6h/anYw/147HfaBzPwfjnRdgwVQ7J7QawO33HaXmFjX017D3wDCzh5kfZ7seNBKSK700XfHtq9S6vcWBaM8RolOlKpma+jCtGMPhtHNqsvzDchImdhvupTaPco6rNXx2BRVxgPlNX+eCy5SNeMSyJyEnbBTu7WdiAIaocjsPDgx2BGdYjTsMQ1RS55la3OUtMiW1XA1kVEblDVD3dvOaP9zaq6UfeWHcdtSpecsqHdPJiFfxPMCPrveGkqNas4h2PmAg4iShwO/DhTRyTab0SnLr+S10+FsayI/e7vDbuewipXd6i1pGLCrND2MOw7K9O39zrmNpVO0b6afVZ2MY2OSeY/HyykZgGOZB81hfGfgb00l22sr0iNjEuh7YrYUuDNsrYDQaQ//La26m3Ni0VRva6q4wqOS+mTk0mrxcLIt6YHi2yF8VcN3EEsOc/rdBZoLdIZH4H9hpdQTce8CVZq6zSxrHdzpx5Ooe1qWOLwTTEPlScxgfKjqM30aJwpd7Wu7kVlSEFIdn/pjKPzdK2wIeY5skOd2XmZvr0PY70bM3i+ELYXBK7vD8EoIj/TXDmm1L6w/2Tg11oSETmQSM0CHMk+agrjdbCIoipW+zr9Jp+EBU/Aym0HAhF5EFgpLySD8Wiqqr4vtz+zOh9Fu+51XuAATRsp/44l0qlkFZYa1QWkYuBOaJsSjMmlcN32Yu6M62CuhyuJyHuxpExJFywRydQTN2KJkbq5XFVCahTIFDMGVw3JrjOG2oVog5pnVSwZU6l+PqFvvxF7kPU5Yk/M1/r7mBukYiuWI7Q9grTXvlMTmKIqLPdh39+QTNLCGEYDZ6jqzr0cX9fP+AxMV1o77rqMOoJ0sIRu+RA6b0Y1y2/qJl0ZE3jz0165YBqt0kd5/oUZnqpaZE+nYnUBVY39WBGRX9BuDY/b1vJ3rtn+81iR2LvCsc8ENUQR22ArIsXcyfpFGGPBQOdiv9GMApkFbeuEZNchn3TnaEqS7gQuonrCrP+jgr69F7Rmvo4qiFUr3xtLQxnbjuYhEdYe6FdDfS8EGbCwiMzWiyq3rjCuY7UfqdwrIrvk9YQisjMwNd9Ye7M617XI9lxdgOLAnUw/3rViixTUKsvQtEX7LVXV7AEmnbkPsr5nwWb9u2HeKKOAJcXCcX/QDzPkhVT1FLG8ENdjVWeKlpTvwX7/riHZNamVdCecs3LCLLUk55m+fXPgZBFp07fXRToDRE7U/ksN8EdM738kFriRMa1I5dWASVrGY8BNQY0Uq/b617UNGC8iR1LBaj+C+Qbwl2ChzkoZrUvIU1By3J4icp9WsDprwp84CKUiKpeLkuqBO2Alg2alVYboS2FfvmJLqlZZhpKrWRY4T0R+hyWY2QPzxT450e7n2Ixo+YSO/hdY4EhfyIT5v0RkCyz16JIFbQ/p47mKmF9qJt0RS4B0JJ0pBFIqoaS+vY9jrhwgUhe1AJyXxKpr/y/63ecRkfVV9bb+OM8A8Ux4jaJmkvy6OuMBsdoPR0Tko5jOTrAMXld3ad/V6iyR47qInKmqX4reK3Tyl1a5qNWwpXRZuajKgTtSM+GT1MxTIFbv8BNh88podhi3qaWjr4qIzKqqb4vIZzGBshStApmHanAvyx1TyUWsh7HUTrojIjdi6T9/jT0Md8Pu54MTbftd3y41AkT6cI4JWPGKbJIxCrizv8/TH4SVwjyq+lxu/6JYhaSuaqGBymc84lFLin5NjUNGicgCOatz/vuPl+p5X+oOx3cJyezV0gVuSivr3f1FN5xa4M4aRCXNKch/ALwrIitocK0SyxRWpv6om6dgMraiUFpFTxNDrqWjr8rTYtnVzgFeVnOD63Z9L0v3kOzaaCi8WfQwKzhsjKpeLSISluiHiMg/MQGd73+L0NeswGoi8rT23SOqcoBIH5D4t1fV6V1WiEPJsVjAUX4V83FMPbRXtw7q5qaYnyg5SbY/ZcF1OoirRMywOufaaMH/qW0wA04m/M5V1W26DUIsP+4etC6as0XkJE1HqMUVWwTzU90t0WftPAViuSl+hD3QBKsJeJiqnpprWktHX4P3YzlRDgL+ICIXYKHThUtgDW500nIROwAztvXZRSxQ52H2RpgpPiiW6/ppYJG4gVgdwONUdYqIzIfl/ngXWFBE9lfVczp6rU6t/Bs98oiI7IupxsCMeo/0Q78DwSaq+rX8TlU9W6zyfVfqqiluJpGcpI4xYWZGzOUsszpfnbc6B6H3HUzf9HPMwk5of5Tm0m3Gao6UGqRgDJMwt7c4x8ItWuACJBbRFueZ7khJKD3kKRALINpIW4mUFsJqE66ca5flEn6dhI5eCyLr6iDmVrcdlmh+kTDmjmxsMkAuYtKb++O6WI6V+bFMefNh18itUZsp2bFiSdk/oqpbi8hiWC2+ngMzBgOxAqDHYveMYqHO+/XDrL7fCfagZPh52Xsxdaf8c6jqt7s3czJqWp2vp1V66HraDWOp1JJlM+nCIdGuashKRrU3sqX4q2oVOebEllrLkXCn0t48Rp7ChHXGNMywlO/7aWD9nI7+8m46+jqoudWdgoVkfxszUKZSYw6Ui1ht90dtRau+IpZj+8WEOid2r9oc8wVGVZ8dILVCfzNdVXcY6kFU5D9i2eXacuqEh2aRq2QbdWfG38KS+JQlJ3EiRORc2q3Oj6nqfl2OqWQIk1YugTiPACSWiiKyTNAXfxvzpb0wvLU1Fop+dNT2ICwHiWLVRj6OubWtj1W0To5fauQpEJE/AB/AgogU+ByWHOoBaHcFCsvxSdrPOUnCg3JLLI/FxpjO70+YMTGpG5cuIdl9HE/Xh5lYBOV5aomVZg9jXgN7SHxRVf8Rtb0WU489jQWHjA2CeBYsK+LY/hh3fyMiWwKnYp/pXeALqdVVkxCR9bCqMadjKzgwz5VdsEjJrh4gdWfGb2HL5x8QJSehOIuXYxFbmdX5FIqz0cVU0h1qvXDWq8WyWv0CE6xZ2aXdVHVCru2OmE51Tsy3dzG17FmzYKHARayeCeIwvhdEpGgp/HB4Zfw1/O1wBwqGm7ulvPp2LcQqKX8cW3H8ERNkpbNcGRgXsZjPi6VDfZ2WkN1PVc+K2mxPq7ZkllVvYSydwBlYvb2Mr2PL/MVCP8+G/R/DZvdN5QjgQ+GBsz6mvkmGGTcFteKw62Gur18Ou6dg+UMqqVXqCuNvAytqheQkzgwqW517MYTV4IOYP/F4YB8tD955Qy2C6C0ReVhD/oMw/rLIoioeI4S+ZvhShxl0apkdszgwRSzgInam7zXg4u+YsHpPlVVI4GjsQXY8Vgih53qBBXxCVQ8USxT1FKbHvhZLHpTxVvQ9fRLTb7+LVdJp+65V9QESkWmq+nfs8zeVd9Qqd6Oqt0l5ZGZjUNX/iMj/8oZ0SRSaTVFXGE+htRR2qlHH6txL6HQl1BznvyUia2Oz5KeISiPlDHhZ0IEA80YPBsEMRUV09RhJLLMvx1KSviMibcvsHMnE+r2SGZ3Fou1KVyHSigJcE1gQC83uzyjAjFnD389gnh3/Szy83wwz9H9jrnj7R+/NmepURI7C0r2WzbibxCLSXmC0bVsrRLMNIbsCecH75cS+DuoK43eBiUEX1S15uEM9VUKPhrDKBCPYMVhJq+Mpzi8SGw9voLshEaicpyC/zB5F8TI77vv6YFR8n6r+IxgVe3Ypq7kKyaIAl9OBiQLMuEREpmJCc2+xJEZ51ck47GGxMJal7NEwns9QUFORajPuJnEy7eqq/HbjkFZR2eWkvRbjPEBHFekUdYXxRVRPTuL0TuXQ6aqIyJ+AJTDdaGkuaA1BCDX6ruMxkl9mn1O0zM6dYw/ga9jMdIXwWU7E9J+9UGcV8llyUYCq+rJYQpup9JMwVtXvihUWeFktqOVVzLAZt7kNGCsiy6vqI9H+y8Qyl6WoMuNuDFpQXqzh1C4q24Gq1nphiWtWC69Z6x7vr0rf8YQq+2r2uUf4u1zivY59Yf84bKYo2Gz6LmyWlW93LjbL+jr2sD66ZBy3hmtnYeB/8bkxP+ai4yaGa29CtG9yP3zXG1Zo80Av7/UwllmBfbGZ7wVY1ZHkPQbcldg3vqDtT7GHxoRwjoWB2/pr3AP1wgx384YxXw08D+w81OMaqFeq/lchIvIRrPrp8VjymAdEpHIlCKcyo8JsGCg3hFVFVbMkPH9OvH1BwWG7q+rLWP6IRbDou58m2q2iqjur6u+wqLayayJbZk+l+jIb4E2N0hKGWXRfwqEz9hSLLM36XUCsFFPMvWJ5e9uQvkcB5jkB01X/NrzWohV9lp1zrIhsQ1CvRK8vU2DkVdXvYpWz11HTb3fMuBvKJ8L191lMvbIS7UExjSP8Fg+KyEsi8rKITItsRqXUvcF/iX1B94cTr4TF9pdWbnVqUyV0uhY9empka9nPAKep6t2SXt/WKWTZyzIbLLXlDzAD6OZYaOwlJe2rUsUdr9dMfXVZV9uTMF0jVkkjplcj7xLA5kGllNEv5aIGkGGlXgkcBWypXYoDpKgrjGfNBDGY64xY8hGnH9EBSNhNbzfxeBG5Eou8+15wMUoZ/XrJU3AB9ZIKfRf4CqaT/jpwGaY66Std3fF0EKIAA10TM2kPRl6xqiofwdJtXoYFH91I84VxFYNm0/h3L4IY6kfgnYrNCrKSKjth5cVrGXycNAlD2Cnafwm7s3PUuYlHYe5cj6jqi2L5I5bQgsrdFfuslYdBLD/B92l9J0eGpWu/IANYNqiHsXwMq9jSlphJVTtS10q9aMfJmDvbBFVdQyyt4+9VtSwPdSMInyszaM6JVY5/tttxQ4VYDubFMNtJ7HGWyundRt2Z8V7Ykm1f7GK5gVbicafvDFjC7oiunhpi+ZFjlu/H5WHdGfofMNXAceG4Y2lFOPWZAVqF9DqWq8WSxpcmZgrUiXZ8XS2K8Z3gkvcfhk/U7HBTr8yLxWJ8ItpXVGChjboz47mw6Kx3w/ZoYHatUaHWKUYGKWG3dk9yn83E5sDUBpMw4bA6ZoXvcy6GqjN0EZmoqmtG24VJ9muef8BXITXGsjN2L56Z278Hlqzpj4lj7qZiVWYR+S02+98Bywr4CjCx6SvaIvWKqm47lOMaKGp5U2DuJWOi7TEUOOk7PdFmCBugc3T11FDVzdQKCTwOrK2q66jq2lhI9UP9NI4qXgzhLVlARBYMYx2d2+6VM7D8EpOxm/wXfeirr3yHtP/+ueG9FJmR93AROQzzcz0q1VBV91bVF1X1RCx7265NF8SBbTE/8mfDeNcAZh/aIZUjIiuJyNUick/YXl0s9WpXekmhOSMeX1VfCXocp38YjITddTw1xmoUIKKq94jImv0wBqi+zJ4PU1PEepKs5mJfklT1ksBpoBitIbIvRi2wJGkgr6teEZHViYpCiMiKVfSYQ8xwVK+cjNlCfgegqpPEklL9uNuBdYXxqyKyloYCpGJ5Dl6v2YdTgNbLwtbrOercxPeJZXo7CxN8O2MJzfuDSkmFVHXZfjpfnsEoG1SVWUVkLg0J/zOC98psuX21qzKHFcfqWG6ZzBumkh5ziLkzrJ5Oxh7IrzC0D80qzKmWwS3eV2mVW1cY74eVEn8mbC+O6aGchtPLTYwFeexFK9z3BnJBCH2gli+1iGyM6TlfDTrWtbBIv15Tag7GKqQqpwAXiMheqvoYgIgsiwVXnZJr24uRdwNVXaUfxzsoqOre4d8TReQKzJOiZ0+eQeJ5EVmBVqX2bbEw6a7UMuCFzmel3drbXxmrnAFEekhyPwhjKi1DlWs7CdMZro65Vp6Czeobnee2KiKyJ/A9rKQT2Czwp6qaj8CrbeQNaphfDpWXSF/Iq1egmpvYUBF8w08CNsIqxzyKhXA/1vXYKsJYRA5U1aPC/9up6vnRez9R1UoF95yho85NLCLnqeoXgn9qqjJzsl5exXH05MWQeVGIpeB8WlVP6S/PiiYhInNj92WHDjm83/aZq3wHYikLLgGexXxfU2lTG0eReiXlS900gufZqKLfMXlMmTAWK9S4GvaEXivsq30xOENPnd9NRBZX1X+JpazMM0rTiderjqOnGbpY3uErMNXJh7G6YhNTrlzDFbH8ztvQORM8LGqTldoC2sptFapXROQhrDBEvpDw4/3+IfoREbl3uKhXpD3/cgdaIQdzN53xmZh7SayNzls6Gh8s7gD1dKSfAM7I36xhRn0mVpapV3r1Ytgeyxf7FbU6bktjeYZHEn8FXsKMVclgjx6NvE+o6sXdmzWOW0RklWGiXulzvuVuwvgOrOZXWRXi/sic5QwwNW/icSIyu6qelO0Iy66LsJp4faG2F0MILjpLVT8eHfsEzY7E6oUlVbWjTFI/MDW4V11CzRDdIeYMTCA3Xr2i/ZCDuVQYqyW7HgNcGM2ixuRmWH2tzeY0j48DV4jIHKp6rFiClsswI9t3+9h3bS8GtbwEr4nIfKr6Uh/P32RuFpEPaJfk/z0wBhNmtUN0h5hTgS+RU680GRFZEgvd3xj7jm/Ecog81fXYut4UzsxBcLK/HNPtfg44QcuLmA70eM4DNgCuor0g6Ygp+SUi92KGzUdp+ExwMBCRa1T1o0M9jjqIyFVYtfEstH1nYCdV3bzrsS6MnTzSync8D/ArLAz+T9n7Q7G8FZFdU/s1FBYdCRQYTPtsaBPLO34CsKiqrhbcxbZS1a5RYUOJWE6N+RlG6hXJ5VIp2pc81oWxk0es6nERQ+ZaFFRmS2uUU3skEXJM/BO4OR+N18d+ryeE6GpICCUi96jqav11joGg4DpstGubiPwDOB0rugFm7N5NVbvWanRh7BQiIsvl3dhS+wZpLFtiyXxmU9XlQo6Mw1R1q8Eey0AhVklkE6xE0jRMMN+gllC+L/3eoarrSpSdr+pszalH8PL5DfYbKpbAaVyV1U3drG3OzEWdenkDzSHAesCLAKo6EatAMmJQ1VPDrG8zLB/IduFvX+k5RHcokT5kQBsqVPUJVd1KVRdW1UVUdeuqaqY+Fbl0RibSW728geYdVX0p5wo3opZ1ISnTKsC/sVnxtrQy1PWFb2AhumNF5GnMQLhTP/Q70PScAW2wyaKUReQ40lGrXQ3NLoydFL0WvRxI7hGRL2L5jN+HVZu5eYjGMlAsBIzGZv//A56vEireDbXCrx+PQ3RFZD/g6L72PcD0nAFtCPi6iNwE3NlrB64zdgqRGvXyBhqxvNk/oOUr+3fgx6ra9AKVtRGR9wOfBL6F5TpecgDO8YSqLt3f/fYnInI58E3g/JCXZFssAvPTQzy0DsLDbXssk+W5WDXribX6cGHsFCE1il4O4BgaUx5poBGRz2IRrx8GFgBuAf6pqqkKKH0915OqulR/99ufFGRA26nJOTWCe+IO4TUH5lVxjqo+2PVYF8ZOEVKhXt4gjKFxqT8HChE5Hrgeq/P2TLf2fTxX42fGGXn1iqoePdRjqoJY5ZpTsao2XdMRuDB2CpEaRS8HcAwDXqS1KYjIcpjhVIH7gq63L/1NI23kFGCMqg47m1HTHyJi+d4/hc2MP4Y9XM9R1Yu6HTvsfgxnUKlVjWOAaFJ5pAEhhJ7/HqvEPRFzOV1DRMZjOtKXSw4vRFX7nEmsgTTyAhCRzbEAjy2wTIR/Ar5WJ3jHZ8ZOKVKjGscAnb92/t7hhoicDjyGBbFMD/sEOAhYUVV3GbrRNYumzoxF5FosJ8WfVfV/PfXhwtjJMzMZzZqAiDyoqu+r+95IZSSqV6owIj+U02d6KXrp9E4jl95DxQhVr3TFZ8ZOBzOT0awJBBfCh4HDNbohReQgYCVV/dKQDc4ZNHxm7KQY8UazhrEPVu36IRGZiC3RPwhMAL46hONyBhGfGTsdzAxGsyYSkvmsgn3PU1T14SEekjOIuDB2nCFGREpVQKraH8mCnIbjwthxhpjgFgUWPrs2MAmbHa8O3KaqmwzV2JzBw/MZO84Qo6qbqepmwOPA2qq6jqqujemNHxra0TmDhQtjx2kOYzWqDK2q9wBrDt1wnMHEvSkcpzncFxLMn4V5VOwM3De0Q3IGC9cZO05DCJGPe2EpNAFuAE4YiTmbnU5cGDtOgxjpFbCdYlxn7DgNQUS2wrK2XRG21xSRi4d0UM6g4cLYcZrDwXRWwF526IbjDCYujB2nObyjqi8N9SCcocG9KRynOcwMFbCdAnxm7DjNYR+s7NKbWCHLl/HUpTMN7k3hOI7TAFxN4ThDTDePCVXdarDG4gwdLowdZ+jZEHgSU03chlf+mClxNYXjDDEiMhrIqguvDlyKlXefMqQDcwYVN+A5zhCjqu+q6hWquiuwAZap7ToR2WeIh+YMIq6mcJwGICKzA1tgs+NlgWOBvwzlmJzBxdUUjjPEhIKkqwGXA38KqTOdmQwXxo4zxIjIdFo1B+Mb0msOzkS4MHYcx2kAbsBzHMdpAC6MHcdxGoALY8dxnAbgwthxHKcB/H/21qTx15ONuQAAAABJRU5ErkJggg==\n",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     },
     "metadata": {
      "needs_background": "light"
     },
     "output_type": "display_data"
    }
   ],
   "source": [
    "import seaborn as sns\n",
    "crimedata.isnull().sum()\n",
    "sns.heatmap(crimedata.isnull(),cmap='viridis',cbar=False,yticklabels=False)\n",
    "\n",
    "plt.title('missing data')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "metadata": {},
   "outputs": [],
   "source": [
    "crimedata = crimedata.rename(columns={'Êcommunityname':'communityName'})\n",
    "cols = ['HousVacant','PctHousOccup','PctHousOwnOcc','PctVacantBoarded','PctVacMore6Mos','PctUnemployed','PctEmploy','murdPerPop','rapesPerPop','robbbPerPop','assaultPerPop','ViolentCrimesPerPop','burglPerPop','larcPerPop','autoTheftPerPop','arsonsPerPop','nonViolPerPop']\n",
    "crimedata.fillna(crimedata[cols].median(),inplace=True)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Data Processing"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>state</th>\n",
       "      <th>ViolentCrimesPerPop</th>\n",
       "      <th>nonViolPerPop</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>AK</td>\n",
       "      <td>576.576667</td>\n",
       "      <td>4961.673333</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>AL</td>\n",
       "      <td>1030.699070</td>\n",
       "      <td>5020.640233</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>AR</td>\n",
       "      <td>718.550400</td>\n",
       "      <td>6509.575600</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>AZ</td>\n",
       "      <td>551.094500</td>\n",
       "      <td>6532.186000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>CA</td>\n",
       "      <td>808.905197</td>\n",
       "      <td>5139.440251</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  state  ViolentCrimesPerPop  nonViolPerPop\n",
       "0    AK           576.576667    4961.673333\n",
       "1    AL          1030.699070    5020.640233\n",
       "2    AR           718.550400    6509.575600\n",
       "3    AZ           551.094500    6532.186000\n",
       "4    CA           808.905197    5139.440251"
      ]
     },
     "execution_count": 43,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "crimedata_state = crimedata.groupby('state').agg({'ViolentCrimesPerPop':'mean','nonViolPerPop':'mean'})[['ViolentCrimesPerPop','nonViolPerPop']].reset_index()\n",
    "crimedata_state.head(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "8940193.0 [17199, 56289.0, 526826.0, 719015.0, 1683856.0, 4728436.0, 1142924.0, 65648.0]\n"
     ]
    }
   ],
   "source": [
    "type_of_criems=['murders', 'rapes', 'robberies', 'assaults', 'burglaries', 'larcenies', 'autoTheft', 'arsons']\n",
    "\n",
    "total_crimes=0\n",
    "crimes= []\n",
    "for i in type_of_criems:\n",
    "    total_crimes+=crimedata[i].sum()\n",
    "    x=crimedata[i].sum()\n",
    "    crimes.append(x)\n",
    "    \n",
    "print(total_crimes,crimes)\n",
    "total_crime='9M'   "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "metadata": {},
   "outputs": [],
   "source": [
    "murders_percentage=(crimes[0]/total_crimes)*100\n",
    "rapes_percentage=(crimes[1]/total_crimes)*100\n",
    "robberies_percentage=(crimes[2]/total_crimes)*100\n",
    "assaults_percentage=(crimes[3]/total_crimes)*100\n",
    "burglaries_percentage=(crimes[4]/total_crimes)*100\n",
    "larcenies_percentage=(crimes[5]/total_crimes)*100\n",
    "autoTheft_percentage=(crimes[6]/total_crimes)*100\n",
    "arsons_percentage=(crimes[7]/total_crimes)*100\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>population</th>\n",
       "      <th>state</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>11980</td>\n",
       "      <td>NJ</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>23123</td>\n",
       "      <td>PA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>29344</td>\n",
       "      <td>OR</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>16656</td>\n",
       "      <td>NY</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>11245</td>\n",
       "      <td>MN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2210</th>\n",
       "      <td>56216</td>\n",
       "      <td>CA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2211</th>\n",
       "      <td>12251</td>\n",
       "      <td>LA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2212</th>\n",
       "      <td>32824</td>\n",
       "      <td>CA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2213</th>\n",
       "      <td>13547</td>\n",
       "      <td>TX</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2214</th>\n",
       "      <td>28898</td>\n",
       "      <td>CA</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>2215 rows × 2 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "      population state\n",
       "0          11980    NJ\n",
       "1          23123    PA\n",
       "2          29344    OR\n",
       "3          16656    NY\n",
       "4          11245    MN\n",
       "...          ...   ...\n",
       "2210       56216    CA\n",
       "2211       12251    LA\n",
       "2212       32824    CA\n",
       "2213       13547    TX\n",
       "2214       28898    CA\n",
       "\n",
       "[2215 rows x 2 columns]"
      ]
     },
     "execution_count": 46,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "crimedata[['population','state']]"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Bar1"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "What is the Crimes Precentage for each City?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th>state</th>\n",
       "      <th>AK</th>\n",
       "      <th>AL</th>\n",
       "      <th>AR</th>\n",
       "      <th>AZ</th>\n",
       "      <th>CA</th>\n",
       "      <th>CO</th>\n",
       "      <th>CT</th>\n",
       "      <th>DC</th>\n",
       "      <th>DE</th>\n",
       "      <th>FL</th>\n",
       "      <th>...</th>\n",
       "      <th>TN</th>\n",
       "      <th>TX</th>\n",
       "      <th>UT</th>\n",
       "      <th>VA</th>\n",
       "      <th>VT</th>\n",
       "      <th>WA</th>\n",
       "      <th>WI</th>\n",
       "      <th>WV</th>\n",
       "      <th>WY</th>\n",
       "      <th>Crimes</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>murders</th>\n",
       "      <td>29.0</td>\n",
       "      <td>326.0</td>\n",
       "      <td>142.0</td>\n",
       "      <td>248.0</td>\n",
       "      <td>3272.0</td>\n",
       "      <td>146.0</td>\n",
       "      <td>195.0</td>\n",
       "      <td>454.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>560.0</td>\n",
       "      <td>...</td>\n",
       "      <td>303.0</td>\n",
       "      <td>1681.0</td>\n",
       "      <td>34.0</td>\n",
       "      <td>355.0</td>\n",
       "      <td>2.0</td>\n",
       "      <td>161.0</td>\n",
       "      <td>199.0</td>\n",
       "      <td>31.0</td>\n",
       "      <td>3.0</td>\n",
       "      <td>murders</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>rapes</th>\n",
       "      <td>249.0</td>\n",
       "      <td>1046.0</td>\n",
       "      <td>636.0</td>\n",
       "      <td>1172.0</td>\n",
       "      <td>9065.0</td>\n",
       "      <td>1238.0</td>\n",
       "      <td>635.0</td>\n",
       "      <td>324.0</td>\n",
       "      <td>36.0</td>\n",
       "      <td>3056.0</td>\n",
       "      <td>...</td>\n",
       "      <td>1351.0</td>\n",
       "      <td>6976.0</td>\n",
       "      <td>432.0</td>\n",
       "      <td>1173.0</td>\n",
       "      <td>41.0</td>\n",
       "      <td>1573.0</td>\n",
       "      <td>904.0</td>\n",
       "      <td>185.0</td>\n",
       "      <td>59.0</td>\n",
       "      <td>rapes</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>robberies</th>\n",
       "      <td>651.0</td>\n",
       "      <td>5836.0</td>\n",
       "      <td>2565.0</td>\n",
       "      <td>5850.0</td>\n",
       "      <td>113334.0</td>\n",
       "      <td>3736.0</td>\n",
       "      <td>6269.0</td>\n",
       "      <td>7107.0</td>\n",
       "      <td>78.0</td>\n",
       "      <td>27216.0</td>\n",
       "      <td>...</td>\n",
       "      <td>7631.0</td>\n",
       "      <td>25285.0</td>\n",
       "      <td>774.0</td>\n",
       "      <td>6627.0</td>\n",
       "      <td>14.0</td>\n",
       "      <td>5480.0</td>\n",
       "      <td>5409.0</td>\n",
       "      <td>573.0</td>\n",
       "      <td>36.0</td>\n",
       "      <td>robberies</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>assaults</th>\n",
       "      <td>1571.0</td>\n",
       "      <td>16086.0</td>\n",
       "      <td>7264.0</td>\n",
       "      <td>16200.0</td>\n",
       "      <td>148772.0</td>\n",
       "      <td>11341.0</td>\n",
       "      <td>5824.0</td>\n",
       "      <td>9003.0</td>\n",
       "      <td>145.0</td>\n",
       "      <td>47525.0</td>\n",
       "      <td>...</td>\n",
       "      <td>12477.0</td>\n",
       "      <td>49564.0</td>\n",
       "      <td>1633.0</td>\n",
       "      <td>8009.0</td>\n",
       "      <td>57.0</td>\n",
       "      <td>10825.0</td>\n",
       "      <td>3873.0</td>\n",
       "      <td>1165.0</td>\n",
       "      <td>365.0</td>\n",
       "      <td>assaults</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>burglaries</th>\n",
       "      <td>2259.0</td>\n",
       "      <td>30462.0</td>\n",
       "      <td>16317.0</td>\n",
       "      <td>45629.0</td>\n",
       "      <td>306585.0</td>\n",
       "      <td>25308.0</td>\n",
       "      <td>27516.0</td>\n",
       "      <td>11532.0</td>\n",
       "      <td>251.0</td>\n",
       "      <td>108475.0</td>\n",
       "      <td>...</td>\n",
       "      <td>30235.0</td>\n",
       "      <td>168969.0</td>\n",
       "      <td>7964.0</td>\n",
       "      <td>24315.0</td>\n",
       "      <td>1048.0</td>\n",
       "      <td>34838.0</td>\n",
       "      <td>21077.0</td>\n",
       "      <td>4025.0</td>\n",
       "      <td>851.0</td>\n",
       "      <td>burglaries</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 49 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "state           AK       AL       AR       AZ        CA       CO       CT  \\\n",
       "murders       29.0    326.0    142.0    248.0    3272.0    146.0    195.0   \n",
       "rapes        249.0   1046.0    636.0   1172.0    9065.0   1238.0    635.0   \n",
       "robberies    651.0   5836.0   2565.0   5850.0  113334.0   3736.0   6269.0   \n",
       "assaults    1571.0  16086.0   7264.0  16200.0  148772.0  11341.0   5824.0   \n",
       "burglaries  2259.0  30462.0  16317.0  45629.0  306585.0  25308.0  27516.0   \n",
       "\n",
       "state            DC     DE        FL  ...       TN        TX      UT       VA  \\\n",
       "murders       454.0    0.0     560.0  ...    303.0    1681.0    34.0    355.0   \n",
       "rapes         324.0   36.0    3056.0  ...   1351.0    6976.0   432.0   1173.0   \n",
       "robberies    7107.0   78.0   27216.0  ...   7631.0   25285.0   774.0   6627.0   \n",
       "assaults     9003.0  145.0   47525.0  ...  12477.0   49564.0  1633.0   8009.0   \n",
       "burglaries  11532.0  251.0  108475.0  ...  30235.0  168969.0  7964.0  24315.0   \n",
       "\n",
       "state           VT       WA       WI      WV     WY      Crimes  \n",
       "murders        2.0    161.0    199.0    31.0    3.0     murders  \n",
       "rapes         41.0   1573.0    904.0   185.0   59.0       rapes  \n",
       "robberies     14.0   5480.0   5409.0   573.0   36.0   robberies  \n",
       "assaults      57.0  10825.0   3873.0  1165.0  365.0    assaults  \n",
       "burglaries  1048.0  34838.0  21077.0  4025.0  851.0  burglaries  \n",
       "\n",
       "[5 rows x 49 columns]"
      ]
     },
     "execution_count": 47,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "crime_type_ber_state=crimedata.groupby(by='state')[['murders', 'rapes', 'robberies', 'assaults', 'burglaries', 'larcenies', 'autoTheft', 'arsons']] .sum()\n",
    "crime_type_ber_state_T = crime_type_ber_state.T\n",
    "crime_type_ber_state_T[\"Crimes\"]=['murders', 'rapes', 'robberies', 'assaults', 'burglaries', 'larcenies', 'autoTheft', 'arsons']\n",
    "crime_type_ber_state_T.head(5)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Bar2"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "What is the 10 Cities with high crime rate?"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "metadata": {},
   "outputs": [],
   "source": [
    "crime_type_ber_state_top=crimedata.groupby(by='state', as_index=False)[['murders', 'rapes', 'robberies', 'assaults', 'burglaries', 'larcenies', 'autoTheft', 'arsons']] .sum()\n",
    "crime_type_top = pd.DataFrame (type_of_criems, columns = ['crime_type'])"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Mab 1"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Showing the distrbution for non-Violent Crimes ber population"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "metadata": {},
   "outputs": [],
   "source": [
    "data1 = dict(type='choropleth',\n",
    "        colorscale = 'Viridis',\n",
    "        autocolorscale = False,\n",
    "        locations = crimedata_state['state'],\n",
    "        locationmode = 'USA-states',\n",
    "        z = crimedata_state['nonViolPerPop'].astype(float),\n",
    "        colorbar = {'title':'non-Violent Crimes'}\n",
    "        )\n",
    "layout1 = dict(\n",
    "        title = 'Aggregate view of non-Violent Crimes Per 100K Population',\n",
    "        geo = dict(\n",
    "            scope='usa',\n",
    "            projection=dict( type='albers usa' ),\n",
    "            showlakes = True,\n",
    "            lakecolor='rgb(85,173,240)'),\n",
    "                )\n",
    "    \n",
    "fig1 = go.Figure(data = [data1],layout = layout1)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Mab 2"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Showing the distrbution for Violent Crimes ber population"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "metadata": {},
   "outputs": [],
   "source": [
    "data2 = dict(type='choropleth',\n",
    "        autocolorscale = False,\n",
    "        colorscale = \"Earth\",\n",
    "        locations = crimedata_state['state'],\n",
    "        locationmode = 'USA-states',\n",
    "        z = crimedata_state['ViolentCrimesPerPop'].astype('float'),\n",
    "        colorbar = {'title':'Violent Crimes'}\n",
    "        )\n",
    "layout2 = dict(\n",
    "        title = 'Aggregate view of Violent Crimes Per 100K Population across US',\n",
    "        geo = dict(\n",
    "            scope='usa',\n",
    "            projection=dict( type='albers usa' ),\n",
    "            showlakes = True,\n",
    "            lakecolor = 'rgb(85,173,240)'),\n",
    "\n",
    "             )\n",
    "    \n",
    "fig2 = go.Figure(data = [data2],layout = layout2)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Mab 3 and 4"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Showing the highest ceties with non-Violent  and Violent crimes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\BS\\AppData\\Local\\Temp/ipykernel_12032/1124230770.py:25: FutureWarning:\n",
      "\n",
      "pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead\n",
      "\n"
     ]
    }
   ],
   "source": [
    "#####thesecond graph cities\n",
    "# Let's find out the outliers in `ViolentCrimesPerPop` response variable and plot those to find cities with highest crime rate in the US\n",
    "quartile_1, quartile_3 = np.percentile(crimedata['ViolentCrimesPerPop'], [25, 75])\n",
    "iqr = quartile_3 - quartile_1\n",
    "lower_bound = quartile_1 - (iqr * 1.5)\n",
    "upper_bound = quartile_3 + (iqr * 1.5)\n",
    "outliers_viol = crimedata.loc[crimedata['ViolentCrimesPerPop']>upper_bound,['communityName','state','ViolentCrimesPerPop']]\n",
    "\n",
    "\n",
    "## Let's find out the outliers in `nonViolPerPop` response variable and plot those to find cities with highest crime rate in the US\n",
    "quartile_1, quartile_3 = np.percentile(crimedata['nonViolPerPop'], [25, 75])\n",
    "iqr = quartile_3 - quartile_1\n",
    "lower_bound = quartile_1 - (iqr * 1.5)\n",
    "upper_bound = quartile_3 + (iqr * 1.5)\n",
    "outliers_nviol = crimedata.loc[crimedata['nonViolPerPop']>upper_bound,['communityName','state','nonViolPerPop']]\n",
    "\n",
    "## Remove community Name(s) ending with \"city\". This helps dataframe(s) merging easier to get lat and lon\n",
    "outliers_viol['communityName'] = outliers_viol['communityName'].map(lambda result : re.sub(r'city','',result))\n",
    "outliers_nviol['communityName'] = outliers_nviol['communityName'].map(lambda result : re.sub(r'city','',result))\n",
    "\n",
    "## read citie.json file to get latitude and longitude details of the cities\n",
    "file = \"cities.json\"\n",
    "with open(file) as city_file:\n",
    "    dict_city = json.load(city_file)\n",
    "    cities_lat_lon = json_normalize(dict_city)\n",
    "\n",
    "## merge cities dataframe(with cities_lat_lon dataframe to get lat and lon of the cities) with outliers_viol dataframe \n",
    "##and outliers_nviol to plot cities with highest violent/non-vilolent crime rate\n",
    "\n",
    "violent_crime_cities = pd.merge(outliers_viol,cities_lat_lon,left_on=[\"communityName\",\"state\"],right_on=[\"city\",\"state\"])\n",
    "violent_crime_cities = violent_crime_cities.drop([\"city\"],axis=1)\n",
    "#print (violent_crime_cities)\n",
    "\n",
    "nonviolent_crime_cities = pd.merge(outliers_nviol,cities_lat_lon,left_on=[\"communityName\",\"state\"],right_on=[\"city\",\"state\"])\n",
    "nonviolent_crime_cities = nonviolent_crime_cities.drop([\"city\"],axis=1)\n",
    "#print (nonviolent_crime_cities)\n",
    "\n",
    "\n",
    "## Cities with highest  non-violent crime rate\n",
    "levels = [(0,20),(21,30),(31,40),(41,50),(51,80)]\n",
    "colors = ['rgb(255,133,27)','rgb(31,120,180)','rgb(178,223,138)','rgb(251,154,153)','rgb(227,26,28)']\n",
    "plot_data = []\n",
    "for i in range(len(levels)):\n",
    "    lim = levels[i]\n",
    "    nonviolent_crime_cities_sub = nonviolent_crime_cities[lim[0]:lim[1]]\n",
    "    city_outline = dict(\n",
    "        type = \"scattergeo\",\n",
    "        locationmode = 'USA-states',\n",
    "        lon = nonviolent_crime_cities_sub['longitude'],\n",
    "        lat = nonviolent_crime_cities_sub['latitude'],\n",
    "        text = nonviolent_crime_cities_sub['communityName'] +' '+ nonviolent_crime_cities_sub['nonViolPerPop'].astype(str),\n",
    "        mode = \"markers\",\n",
    "        marker = dict(\n",
    "        size = nonviolent_crime_cities_sub['nonViolPerPop']/800,\n",
    "        color = colors[i],\n",
    "        ),  \n",
    "    name = '{0} - {1}'.format(lim[0],lim[1])\n",
    "    )\n",
    "    layout1 = dict(\n",
    "        title = 'Cities with highest non-Violent Crime rate',\n",
    "        geo = dict(\n",
    "            scope='usa',\n",
    "            projection=dict( type='albers usa' ),\n",
    "            showlakes = True,\n",
    "            lakecolor = 'rgb(85,173,240)'), \n",
    "    )\n",
    "    plot_data.append(city_outline)\n",
    "    \n",
    "fig3= dict( data=plot_data, layout=layout1)\n",
    "    \n",
    "    \n",
    "## Cities with highest violent crime rate\n",
    "levels = [(0,30),(31,60),(61,90),(91,120),(121,170)]\n",
    "colors = ['rgb(175,175,50)','rgb(131,120,180)','rgb(78,230,138)','rgb(251,24,153)','rgb(227,126,28)']\n",
    "cities = []\n",
    "for i in range(len(levels)):\n",
    "    lim = levels[i]\n",
    "    violent_crime_cities_sub = violent_crime_cities[lim[0]:lim[1]]\n",
    "    city_outline = dict(\n",
    "        type = \"scattergeo\",\n",
    "        locationmode = 'USA-states',\n",
    "        lon = violent_crime_cities_sub['longitude'],\n",
    "        lat = violent_crime_cities_sub['latitude'],\n",
    "        text = violent_crime_cities_sub['communityName'] +' '+ violent_crime_cities_sub['ViolentCrimesPerPop'].astype(str),\n",
    "        mode = \"markers\",\n",
    "        marker = dict(\n",
    "        size = violent_crime_cities_sub['ViolentCrimesPerPop']/200,\n",
    "        color = colors[i]\n",
    "        ),  \n",
    "    name = '{0} - {1}'.format(lim[0],lim[1])\n",
    "    )\n",
    "    layout2 = dict(\n",
    "        title = 'Cities with highest Violent Crime rate',\n",
    "        geo = dict(\n",
    "            scope='usa',\n",
    "            projection=dict( type='albers usa' ),\n",
    "            showlakes = True,\n",
    "            lakecolor = 'rgb(85,173,240)'),\n",
    "    ) \n",
    "    cities.append(city_outline)\n",
    "    \n",
    "fig4= dict( data=cities, layout=layout2)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# BANS"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "metadata": {},
   "outputs": [],
   "source": [
    "bans_style={'margin': 12,\n",
    "            'width': 150, \n",
    "            'border-radius': '80px',\n",
    "            \"border\": \"3px solid black\",\n",
    "            'backgroundColor': 'white', \n",
    "            'padding': 10, \n",
    "            'float': 'left',\"text-align\": \"left!important\"}\n",
    "\n",
    "bans_header_style={'fontSize': 18,\n",
    "              'color': 'gray',\n",
    "              \"text-align\": \"center\"}\n",
    "\n",
    "\n",
    "bans=dbc.Col(children=[\n",
    "        dbc.Row(children=[\n",
    "            \n",
    "            \n",
    "            dbc.Col(html.Div(className=\"summary-1\", children=[\n",
    "            html.H6('Larcenies', className='my-class', style=bans_header_style),\n",
    "            html.H5(f\"{larcenies_percentage:,.2f}%\", className='my-class', \n",
    "                    style={'color': '#19D3F3',\"text-align\": \"center\",\n",
    "                          'font-size': '36px','font-weight': 'bold'})],\n",
    "                 style=bans_style)),\n",
    "            \n",
    "            \n",
    "            dbc.Col(html.Div(className=\"summary-1\", children=[\n",
    "            html.H6('Burglaries', className='my-class', style=bans_header_style),\n",
    "            html.H5(f\"{burglaries_percentage:,.2f}%\", className='my-class', \n",
    "                    style={'color': '#FFA15A',\"text-align\": \"center\",\n",
    "                          'font-size': '36px','font-weight': 'bold'})],\n",
    "                 style=bans_style)),\n",
    "                      \n",
    "            \n",
    "            dbc.Col( html.Div(className=\"summary-1\", children=[\n",
    "            html.H6('AutoTheft', className='my-class', style=bans_header_style),\n",
    "            html.H5(f\"{autoTheft_percentage:,.2f}%\", className='my-class', style=\n",
    "                    {'color': '#FF6692',\"text-align\": \"center\",\n",
    "                      'font-size': '36px','font-weight': 'bold'})],\n",
    "                 style=bans_style)),\n",
    "            \n",
    "            \n",
    "            \n",
    "            dbc.Col(html.Div(className=\"summary-1\", children=[\n",
    "            html.H6('Assaults', className='my-class', style=bans_header_style),\n",
    "            html.H5(f\"{assaults_percentage:,.2f}%\", className='my-class', \n",
    "                    style={'color': '#AB63FA',\"text-align\": \"center\",\n",
    "                          'font-size': '36px','font-weight': 'bold'})],\n",
    "                 style=bans_style)),\n",
    "    \n",
    "        ]), \n",
    "    \n",
    "    \n",
    "    dbc.Row(children=[\n",
    "        \n",
    "        \n",
    "            dbc.Col( html.Div(className=\"summary-1\", children=[\n",
    "            html.H6('Robberies', className='my-class', style=bans_header_style),\n",
    "            html.H5(f\"{robberies_percentage:,.2f}%\", className='my-class',\n",
    "                    style={'color': '#00CC96',\"text-align\": \"center\",\n",
    "                          'font-size': '36px','font-weight': 'bold'})],\n",
    "                 style=bans_style)),\n",
    "                      \n",
    "        \n",
    "            dbc.Col( html.Div(className=\"summary-1\", children=[\n",
    "            html.H6('Arsons', className='my-class', style=bans_header_style),\n",
    "            html.H5(f\"{arsons_percentage:,.2f}%\", className='my-class', \n",
    "                    style={'color': '#B6E880',\"text-align\": \"center\",\n",
    "                          'font-size': '36px','font-weight': 'bold'})],\n",
    "                 style=bans_style)),\n",
    "        \n",
    "        \n",
    "            dbc.Col( html.Div(className=\"summary-1\", children=[\n",
    "            html.H6('Rapes', className='my-class', style=bans_header_style),\n",
    "            html.H5(f\"{rapes_percentage:,.2f}%\", className='my-class',\n",
    "                    style={'color': '#EF553B',\"text-align\": \"center\",\n",
    "                           'font-size': '36px','font-weight': 'bold'})],\n",
    "                 style=bans_style)),\n",
    "        \n",
    "        \n",
    "             \n",
    "            dbc.Col(html.Div(className=\"summary-1\", children=[\n",
    "            html.H6('Murders', className='my-class',\n",
    "                    style=bans_header_style),\n",
    "            html.H5(f\"{murders_percentage:,.2f}%\", className='my-class', \n",
    "                    style={'color': '#959FF9',\"text-align\": \"center\",\n",
    "                          'font-size': '36px','font-weight': 'bold'})],\n",
    "                   style=bans_style)),\n",
    "            ])],\n",
    "             style={\"width\":\"60%\",\"align-items\":\"center\" ,'display': 'inline-block'})\n",
    "\n",
    "circle=html.Div(className=\"graphs-summary\", children=[\n",
    "    dbc.Row(children=[\n",
    "    dbc.Col(html.Div(className=\"summary-1\", children=[\n",
    "            html.H6('Total Crimes', className='my-class',\n",
    "                    style={'fontSize': 28,\n",
    "                           'color': 'gray',\n",
    "                           \"padding-top\": \"28px\"}),\n",
    "        \n",
    "            html.H5(total_crime, className='my-class', \n",
    "                    style={'color': '#FFA15A',\"text-align\": \"center\",\n",
    "                          'font-size': '52px','font-weight': 'bold'})],\n",
    "                     \n",
    "                 style={'margin': 12,\n",
    "                        'width': \"200px\",\n",
    "                        \"border\": \"3px solid black\",\n",
    "                        \"height\":\"200px\",\n",
    "                        'border-radius': '200px'\n",
    "                        ,'backgroundColor': 'white', \n",
    "                        'float': 'left', 'padding': 14,\n",
    "                        \"text-align\": \"center\",\n",
    "                         'margin-top': '-40px'}),\n",
    "  \n",
    "            \n",
    "            )])],style={\"width\":\"18%\",\n",
    "                        \"height\":\"237px\", \n",
    "                        'display': 'inline-block',\n",
    "                        \"padding-left\": \"218px\"})\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Putting the graph to DashBoard"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 53,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<dash.dash.Dash at 0x1f58d7ea820>"
      ]
     },
     "execution_count": 53,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "app = dash.Dash(name=\" UCI Crime and Communities\",external_stylesheets=['https://codepen.io/chriddyp/pen/bWLwgP.css',\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\"])\n",
    "app"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 59,
   "metadata": {},
   "outputs": [],
   "source": [
    "st_border={ \"border\": \"10px solid #a95b0c\",\n",
    " \"border-radius\": \"22px\",\n",
    "  \"margin\": \"9px 7px\"}\n",
    "\n",
    "\n",
    "bars=html.Div(children=[html.Div(className=\"summary-1\", children=[\n",
    "                dcc.Dropdown(\n",
    "                id=\"dropdown2\",\n",
    "                options = [{'label': str(crime_type), \n",
    "                            'value': str(crime_type)} for crime_type in crime_type_top['crime_type'].unique()],\n",
    "                value=\"murders\",\n",
    "                clearable=False,\n",
    "                style={\"margin-bottom\": \"10px\"}\n",
    "                ),\n",
    "                dcc.Graph(id=\"graph2\",style=st_border),],style={'width': '49%', \n",
    "                                                                'display': 'inline-block',\n",
    "              'vertical-align': 'middle', \"padding\": \"40px 10px 10px 0px\"},),           \n",
    "            html.Div(className=\"summary-1\", children=[\n",
    "                dcc.Dropdown(\n",
    "                id=\"dropdown1\",\n",
    "                options = [{'label': str(state), 'value': str(state)} for state in crimedata['state'].unique()],\n",
    "                value=\"TX\",\n",
    "                clearable=False,\n",
    "                style={\"margin-bottom\": \"10px\"}),\n",
    "                dcc.Graph(id=\"graph1\",style=st_border),],style={'width': '49%', \n",
    "                               'display': 'inline-block', \n",
    "                                'vertical-align': 'middle',\n",
    "                                \"padding\":\"40px 10px 10px 0px\"},)])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 60,
   "metadata": {},
   "outputs": [],
   "source": [
    "maps=html.Div(children=[\n",
    "            html.Div(className=\"summary-1\", children=[\n",
    "            dcc.Graph(\n",
    "                id='example-map',\n",
    "                className='six column',\n",
    "                figure=fig1\n",
    "                ),],\n",
    "                      style={'width': '48%', \n",
    "                            'display': 'inline-block', \n",
    "                            \"border\": \"10px solid #a95b0c\",\n",
    "                            \"border-radius\": \"22px\",\n",
    "                            \"margin\": \"24px 0px 10px 0px\"},),\n",
    "\n",
    "                        \n",
    "            html.Div(className=\"summary-1\", children=[\n",
    "                dcc.Graph(\n",
    "                className='six column',\n",
    "                figure=fig2\n",
    "                ),],\n",
    "                     style={'width': '48%',\n",
    "                            'display': 'inline-block',\n",
    "                            \"border\": \"10px solid #a95b0c\",\n",
    "                             \"border-radius\": \"22px\",\n",
    "                              \"margin\":\"24px 0px 10px 12px\"}),\n",
    "                        \n",
    "                        \n",
    "            html.Div(className=\"summary-1\", children=[\n",
    "                dcc.Graph(\n",
    "                className='six column',\n",
    "                figure=fig3\n",
    "                ),],style={'width': '48%', \n",
    "                            'display': 'inline-block', \n",
    "                            \"border\": \"10px solid #a95b0c\",\n",
    "                            \"border-radius\": \"22px\",\n",
    "                            \"margin\": \"24px 0px 10px 0px\"}),\n",
    "                        \n",
    "                        \n",
    "                        \n",
    "                        \n",
    "            html.Div(className=\"summary-1\", children=[\n",
    "                dcc.Graph(\n",
    "                className='six column',\n",
    "                figure=fig4\n",
    "                ),],style={'width': '48%',\n",
    "                            'display': 'inline-block',\n",
    "                            \"border\": \"10px solid #a95b0c\",\n",
    "                             \"border-radius\": \"22px\",\n",
    "                              \"margin\":\"24px 0px 10px 12px\"})\n",
    "                       ])\n",
    "                \n",
    "                "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 62,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "        <iframe\n",
       "            width=\"100%\"\n",
       "            height=\"650\"\n",
       "            src=\"http://127.0.0.1:8050/\"\n",
       "            frameborder=\"0\"\n",
       "            allowfullscreen\n",
       "            \n",
       "        ></iframe>\n",
       "        "
      ],
      "text/plain": [
       "<IPython.lib.display.IFrame at 0x1f58d7e5280>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "title_style={   'text-align': 'center',\n",
    "                'margin-bottom': '0px',\n",
    "                'font-size': '80px',\n",
    "                'font-weight': 'bold',\n",
    "                'padding-top': '20px',\n",
    "                'padding-bottom': '61px',\n",
    "                'color': \"#a95b0c\"}\n",
    "\n",
    "\n",
    "app.layout = html.Div([\n",
    "                    html.Div([\n",
    "            html.Div([\n",
    "                html.H3(\"UCI Crime and Communities\", style=title_style),\n",
    "                ])\n",
    "        ], className=\"six column\", id=\"title\"),\n",
    "    #################################################################################################################\n",
    "     # Summary Div Design\n",
    "    html.Div(className=\"graphs-summary\", children=[ circle,\n",
    "        bans\n",
    "         ,html.Div(style={'width': '100%', \n",
    "                          \"border\": \"1px solid #a95b0c\",\n",
    "                          \"margin\": \"24px 0px 10px 0px\"} )                                        \n",
    "      ,bars,\n",
    "       maps\n",
    "    ]),])\n",
    "    \n",
    "\n",
    "@app.callback(\n",
    "    Output(\"graph1\", \"figure\"), \n",
    "    Input(\"dropdown1\", \"value\"))\n",
    "def update_bar_chart(state):\n",
    "    df = crime_type_ber_state_T # replace with your own data source\n",
    "    mask =df[state]\n",
    "    fig1 = px.bar(df, x=\"Crimes\", y=mask, text_auto=True,color=\"Crimes\")\n",
    "    fig1.update_layout(uniformtext_minsize=8, uniformtext_mode='hide', xaxis_tickangle=-90,\\\n",
    "                   title={'text': 'Crimes Precentage by State','y':0.96,'x':0.5, 'xanchor': 'center','yanchor': 'top'})\n",
    "  \n",
    "    return fig1\n",
    "\n",
    "\n",
    "@app.callback(\n",
    "    Output(\"graph2\", \"figure\"), \n",
    "    Input(\"dropdown2\", \"value\"))\n",
    "def update_bar_chart(crime):\n",
    "    df =crime_type_ber_state_top.sort_values(by=crime ,ascending=False)[0:10] # replace with your own data source\n",
    "    mask = df[crime] \n",
    "    fig2 = px.bar(df, x=\"state\", y=mask , text_auto=True,color=mask)\n",
    "    fig2.update_layout(uniformtext_minsize=8, uniformtext_mode='hide', xaxis_tickangle=-90,\\\n",
    "                   title={'text': 'Top 10 State','y':0.96,'x':0.5, 'xanchor': 'center','yanchor': 'top'})\n",
    "    return fig2\n",
    "\n",
    "\n",
    "app.run_server()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
