services:
  - type: web
    name: my-dash-service
    env: python
    plan: free
    buildCommand: 'pip install -r requirements.txt'
    startCommand: 'gunicorn app:server -b 0.0.0.0:$PORT'
    envVars:
      - key: PORT
        value: 10000  # or another port number if needed
